import type {Recipe} from '../domain/types';
import {generateAiRecipe} from './aiProposalGateway';
import {compatible,recipeNutrition,type PlanOptions,type Meal,type Nutrients} from './mealPlan';
import {validateRecipe} from './recipeValidator';
export function percentageMacros(kcal:number,protein:number,carbs:number,fat:number){if(![kcal,protein,carbs,fat].every(Number.isFinite)||kcal<=0||[protein,carbs,fat].some(v=>v<0)||Math.abs(protein+carbs+fat-100)>.1)throw Error('Los porcentajes de proteínas, hidratos y grasas deben sumar 100 %.');return {proteinG:kcal*protein/100/4,carbsG:kcal*carbs/100/4,fatG:kcal*fat/100/9};}
export function planNutrition(recipe:Recipe,servings:number):Nutrients{const computed=recipeNutrition(recipe,servings);if(recipe.source?.kind!=='ai'||recipe.nutritionStatus==='unavailable')return computed;const n=recipe.nutritionPerServing;if(!n)return computed;return {kcal:computed.kcal??n.kcal,proteinG:computed.proteinG??n.proteinG,carbsG:computed.carbsG??n.carbsG,fatG:computed.fatG??n.fatG,fiberG:computed.fiberG??n.fiberG??null};}
export async function generatePlanMeal(o:PlanOptions,meal:Meal,previous:string[],language:string,change='',current?:Recipe):Promise<Recipe>{
 const target=o.goal?o.goal.kcal*o.shares[meal]/100:undefined;
 const macros=o.goal?['proteinG','carbsG','fatG','fiberG'].flatMap(key=>{const value=o.goal?.[key as keyof typeof o.goal];return typeof value==='number'?[`${key}: ${(value*o.shares[meal]/100).toFixed(1)} g por persona`]:[]}).join(', '):'';
 const recipe=await generateAiRecipe({mode:'desire',generationMode:'ai',servings:o.servings,pantryBasics:[],cuisine:o.cuisine||undefined,style:o.style||undefined,maxMinutes:o.maxMinutes,restrictions:o.restrictions,language,desireText:`Crea una comida completa y práctica para ${meal}, con todos sus componentes y cantidades para ${o.servings} personas. Puede ser un desayuno o merienda sencillo, no necesita ser una receta de cocina elaborada. Devuelve mealType=${meal}. ${target?`Objetivo aportado por el usuario: aproximadamente ${Math.round(target)} kcal POR PERSONA en esta comida; no lo cambies.`:'El usuario no ha definido calorías; no prescribas un objetivo.'} ${macros?`Reparto aportado por el usuario para esta comida: ${macros}.`:'Propón una distribución de alimentos variada; los macros resultantes serán una propuesta para revisar.'} Gustos: ${o.likes||'variados'}. Alterna grupos y proteínas; evita repetir estos platos: ${previous.slice(-35).join('; ')}. ${current?`Buscamos una alternativa SIMILAR a ${current.title}; conserva la función de esta comida y explica en description por qué puede sustituirla, sin afirmar equivalencia exacta.`:''} ${change?`Cambio solicitado: ${change}`:''} No uses alcohol ni suplementos. No prescribas déficits, tratamientos o pérdida de peso. Incluye una estimación nutricional por persona, incluida fibra solo si se puede estimar, y explica que es orientativa.`},{id:'meal-plan',recipeId:'meal-plan',title:current?`Alternativa a ${current.title}`:`${meal} del plan`,subtitle:'Propuesta de comida con IA',emoji:'🍽️',minutes:o.maxMinutes??30,difficulty:'Fácil',usedIngredients:[],missingIngredients:[],reason:'Plan generado a petición del usuario'});
 if(!validateRecipe(recipe).valid||!compatible(recipe,o,meal))throw Error(`La propuesta de ${meal.toLowerCase()} no cumple las condiciones. No se ha incorporado; puedes reintentar o ajustar el plan.`);
 return {...recipe,id:'plan-ai-'+crypto.randomUUID(),nutritionStatus:'estimated',source:{...recipe.source!,kind:'ai',label:'Propuesta de plan con IA · revisar'}};
}
