import type { CookingRequest, Difficulty, DishClassification, NutritionSummary, Proposal, Recipe } from '../domain/types';
const API_URL=(import.meta.env.VITE_RECIPE_API_URL||'https://nrtmmepynzczfdddvohh.supabase.co/functions/v1').trim().replace(/\/+$/,'');const API_KEY=(import.meta.env.VITE_RECIPE_API_KEY||'sb_publishable_b08-tfZCh2pEBGK0lBH-1g_oB3RwvV8').trim();const SUGGEST_TIMEOUT_MS=65000,GENERATE_TIMEOUT_MS=120000,REVISE_TIMEOUT_MS=120000,PROPOSAL_COUNT=2;
export function isAiProposalApiConfigured(){return Boolean(API_URL&&API_KEY)}
export async function fetchAiProposals(request:CookingRequest){const payload=await postJson('/recipes/suggest',{request},SUGGEST_TIMEOUT_MS),items=isRecord(payload)&&Array.isArray(payload.proposals)?payload.proposals:[];return items.map(toProposal).filter((i):i is Proposal=>Boolean(i)).slice(0,PROPOSAL_COUNT)}
export async function generateAiRecipe(request:CookingRequest,proposal:Proposal):Promise<Recipe>{return extractAiRecipe(await postJson('/recipes/generate',{request,proposal},GENERATE_TIMEOUT_MS),'La IA no ha devuelto una receta completa utilizable.')}
export async function reviseAiRecipe(recipe:Recipe,instruction:string,servings?:number):Promise<Recipe>{const clean=instruction.trim();if(!clean)throw new Error('Indica qué quieres cambiar en la receta.');return extractAiRecipe(await postJson('/recipes/revise',{recipe,instruction:clean,servings},REVISE_TIMEOUT_MS),'La IA no ha devuelto una versión revisada utilizable.')}
function extractAiRecipe(payload:unknown,fallback:string):Recipe{const c=isRecord(payload)&&Array.isArray(payload.recipes)?payload.recipes:[],v=c.find(i=>isRecord(i)&&isRecord(i.source)&&i.source.kind==='ai');if(!v)throw new Error(fallback);return v as Recipe}
async function postJson(path:string,body:unknown,timeoutMs:number){const controller=new AbortController(),timer=window.setTimeout(()=>controller.abort(),timeoutMs);try{const response=await fetch(`${API_URL}${path}`,{method:'POST',headers:{'Content-Type':'application/json',apikey:API_KEY,Authorization:`Bearer ${API_KEY}`},body:JSON.stringify(body),signal:controller.signal});const payload=await response.json().catch(()=>undefined);if(!response.ok)throw new Error(describeError(response.status,payload));return payload}catch(e){if(e instanceof DOMException&&e.name==='AbortError'){if(path.endsWith('/suggest'))throw new Error('La IA ha superado el tiempo máximo. Puedes repetir la búsqueda.');if(path.endsWith('/revise'))throw new Error('La IA ha tardado demasiado en revisar la receta. El original sigue intacto.');throw new Error('La IA ha tardado demasiado en completar la receta. Puedes reintentar sin repetir la búsqueda.')}throw e}finally{window.clearTimeout(timer)}}
function toProposal(v:unknown):Proposal|undefined{if(!isRecord(v))return;const difficulty=asDifficulty(v.difficulty),classification=asClassification(v.classification);if(!text(v.id)||!text(v.title)||!text(v.subtitle)||!text(v.emoji)||!number(v.minutes)||!difficulty||!text(v.reason))return;return{id:v.id.trim(),title:v.title.trim(),subtitle:v.subtitle.trim(),emoji:v.emoji.trim(),minutes:v.minutes,difficulty,style:text(v.style)?v.style.trim():undefined,classification,usedIngredients:strings(v.usedIngredients),missingIngredients:strings(v.missingIngredients),insufficientIngredients:strings(v.insufficientIngredients),substitutionNotes:strings(v.substitutionNotes),reason:v.reason.trim(),recipeId:text(v.recipeId)?v.recipeId.trim():v.id.trim(),nutritionPerServing:asNutrition(v.nutritionPerServing)}}
function asNutrition(v:unknown):NutritionSummary|undefined{if(!isRecord(v))return;const kcal=finite(v.kcal),proteinG=finite(v.proteinG),carbsG=finite(v.carbsG),fatG=finite(v.fatG);if(kcal===undefined||proteinG===undefined||carbsG===undefined||fatG===undefined)return;const fiberG=finite(v.fiberG);return{kcal,proteinG,carbsG,fatG,...(fiberG!==undefined?{fiberG}:{})}}
function describeError(status:number,payload:unknown){const d=isRecord(payload)?payload:{},code=typeof d.errorCode==='string'?d.errorCode:undefined,message=typeof d.errorMessage==='string'?d.errorMessage:undefined;if(status===429)return'La IA no tiene cuota disponible ahora mismo.';if(status===401||status===403)return`La IA ha rechazado la autenticación${code?` (${code})`:''}.`;if(status>=500)return`La IA ha tenido un fallo temporal${code?` (${code})`:''}. Puedes repetir la búsqueda.`;if(message)return`La generación con IA ha fallado${code?` (${code})`:''}: ${sanitize(message)}`;return`La generación con IA ha fallado (error ${status}).`}
function sanitize(m:string){return m.replace(/sk-[A-Za-z0-9_-]+/g,'sk-…').slice(0,180)}function asDifficulty(v:unknown):Difficulty|undefined{return v==='Fácil'||v==='Media'||v==='Avanzada'?v:undefined}function asClassification(v:unknown):DishClassification|undefined{return v==='Con lo que tienes'||v==='Te falta muy poco'||v==='Buena opción si compras algunas cosas'?v:undefined}function strings(v:unknown){return Array.isArray(v)?v.filter(text).map(i=>i.trim()).filter(Boolean):[]}function text(v:unknown):v is string{return typeof v==='string'&&Boolean(v.trim())}function number(v:unknown):v is number{return typeof v==='number'&&Number.isFinite(v)&&v>0}function finite(v:unknown){return typeof v==='number'&&Number.isFinite(v)?v:undefined}function isRecord(v:unknown):v is Record<string,any>{return typeof v==='object'&&v!==null&&!Array.isArray(v)}
