export function textFromRecipeHtml(html:string):{text:string;author:string;title:string}{
 const doc=new DOMParser().parseFromString(html,'text/html');
 const find=(v:unknown):any=>{if(Array.isArray(v)){for(const x of v){const hit=find(x);if(hit)return hit;}}else if(v&&typeof v==='object'){const o=v as Record<string,unknown>;if([o['@type']].flat().includes('Recipe'))return o;for(const x of Object.values(o)){const hit=find(x);if(hit)return hit;}}};
 for(const node of doc.querySelectorAll('script[type="application/ld+json"]')){try{const recipe=find(JSON.parse(node.textContent??''));if(recipe){const plain=(x:any):string=>typeof x==='string'?x:Array.isArray(x)?x.map(plain).join('\n'):x&&typeof x==='object'?plain(x.text??x.itemListElement??x.name??''):'';const title=plain(recipe.name);return {text:[title,plain(recipe.description),'Comensales: '+plain(recipe.recipeYield),'Ingredientes',plain(recipe.recipeIngredient),'Elaboración',plain(recipe.recipeInstructions)].join('\n'),author:plain(recipe.author),title};}}catch{/* Invalid metadata is not executable. */}}
 const meta=(...names:string[])=>{for(const name of names){const el=doc.querySelector(`meta[property="${name}"],meta[name="${name}"]`);const value=el?.getAttribute('content')?.trim();if(value)return value;}return '';};
 const title=meta('og:title','twitter:title')||doc.title.trim();
 const description=meta('og:description','twitter:description','description');
 const author=meta('author','article:author');
 if(description.length>=80)return {text:[title,description].filter(Boolean).join('\n\n'),author,title};
 doc.querySelectorAll('script,style,nav,header,footer,aside,form').forEach(n=>n.remove());const root=doc.querySelector('article,main')??doc.body;root.querySelectorAll('br').forEach(n=>n.replaceWith('\n'));root.querySelectorAll('p,li,h1,h2,h3').forEach(n=>n.append('\n'));const text=(root.textContent??'').replace(/[ \t]+/g,' ').replace(/\n\s*\n/g,'\n').trim();if(text.length<80)throw Error('La fuente no expone suficiente contenido público. Pega la descripción, el texto o la transcripción y The Chef continuará desde ahí.');if(text.length>50000)throw Error('La página contiene demasiado texto. Pega solo la receta o la transcripción.');return {text,author,title};
}
