import type { CookingRequest, Difficulty, Proposal, Recipe } from '../domain/types';
import { evaluateRecipePantry, formatInsufficientIngredient, ingredientMatch, type PantryIngredientEvaluation } from './pantryEvaluation';
import { getAllRecipes } from './recipeCatalog';
const difficultyRank:Record<Difficulty,number>={'Fácil':1,'Media':2,'Avanzada':3}; type RankedRecipe={recipe:Recipe;score:number;evaluations:PantryIngredientEvaluation[]};
export function getMockProposals(request:CookingRequest,excludeRecipeIds:string[]=[]):Proposal[]{const query=normalize(request.desireText??'');const priorities=(request.pantryIngredients??[]).filter(i=>i.priority);const catalog=getAllRecipes();const candidates=catalog.filter(r=>!excludeRecipeIds.includes(r.id));const pool=candidates.length>=2?candidates:catalog;const ranked:RankedRecipe[]=pool.map(recipe=>{const evaluations=request.mode==='pantry'?evaluateRecipePantry(recipe,request).filter(e=>!e.ingredient.optional):[];let score=0;if(request.mode==='pantry'){const available=evaluations.filter(i=>i.status==='available').length,sub=evaluations.filter(i=>i.status==='substituted').length,ins=evaluations.filter(i=>i.status==='insufficient').length,miss=evaluations.filter(i=>i.status==='missing').length;const used=priorities.filter(p=>recipe.ingredients.some(i=>ingredientMatch(i.name,p.name))).length;const coverage=evaluations.length?(available+sub*.75+ins*.35)/evaluations.length:0;score+=available*10+sub*5+ins-miss*8+coverage*12+used*24-Math.max(0,priorities.length-used)*12}else score+=textAffinity(recipe,query)*10;if(request.maxMinutes){const total=recipe.prepMinutes+recipe.cookMinutes;score+=total<=request.maxMinutes?10:-Math.min(40,(total-request.maxMinutes)*1.6)}if(request.cuisine)score+=normalize(recipe.cuisine)===normalize(request.cuisine)?11:-2;if(request.style&&request.style!=='Indiferente')score+=normalize(recipe.style)===normalize(request.style)?9:-1;if(request.difficulty)score+=difficultyRank[recipe.difficulty]<=difficultyRank[request.difficulty]?6:-12;return{recipe,score,evaluations}}).sort((a,b)=>b.score-a.score);return selectDiverse(ranked,2).map((item,index)=>toProposal(item,request,index))}
function selectDiverse(ranked:RankedRecipe[],limit:number){const selected:RankedRecipe[]=[],remaining=[...ranked];while(selected.length<limit&&remaining.length){let bi=0,bs=-Infinity;remaining.forEach((c,i)=>{const s=c.score-selected.reduce((sum,ch)=>sum+similarityPenalty(c.recipe,ch.recipe),0);if(s>bs){bs=s;bi=i}});selected.push(remaining.splice(bi,1)[0])}return selected}
function similarityPenalty(a:Recipe,b:Recipe){let p=0;if(normalize(a.cuisine)===normalize(b.cuisine))p+=3;if(normalize(a.style)===normalize(b.style))p+=2;const aa=new Set(a.ingredients.filter(i=>!i.optional).map(i=>normalize(i.name))),bb=new Set(b.ingredients.filter(i=>!i.optional).map(i=>normalize(i.name)));const inter=[...aa].filter(i=>bb.has(i)).length,union=new Set([...aa,...bb]).size,overlap=union?inter/union:0;if(overlap>=.65)p+=10;else if(overlap>=.45)p+=5;return p}
function base(recipe:Recipe){return{style:recipe.style,nutritionPerServing:{...recipe.nutritionPerServing},title:recipe.title,subtitle:recipe.description,emoji:recipe.emoji,minutes:recipe.prepMinutes+recipe.cookMinutes,difficulty:recipe.difficulty,recipeId:recipe.id}}
function toProposal(item:RankedRecipe,request:CookingRequest,index:number):Proposal{const{recipe,evaluations}=item;if(request.mode==='desire')return{id:`proposal-${recipe.id}`,...base(recipe),usedIngredients:recipe.ingredients.slice(0,4).map(i=>i.name),missingIngredients:[],reason:desireReason(index)};const available=evaluations.filter(e=>e.status==='available'),sub=evaluations.filter(e=>e.status==='substituted'),ins=evaluations.filter(e=>e.status==='insufficient'),missing=evaluations.filter(e=>e.status==='missing'),issue=ins.length+missing.length,priorities=(request.pantryIngredients??[]).filter(p=>p.priority),used=priorities.filter(p=>recipe.ingredients.some(i=>ingredientMatch(i.name,p.name)));return{id:`proposal-${recipe.id}`,...base(recipe),classification:issue===0?'Con lo que tienes':issue===1?'Te falta muy poco':'Buena opción si compras algunas cosas',usedIngredients:available.map(e=>e.pantryItem?.name??e.ingredient.name).slice(0,5),missingIngredients:missing.map(e=>e.ingredient.name).slice(0,4),insufficientIngredients:ins.map(formatInsufficientIngredient).slice(0,3),substitutionNotes:sub.map(e=>`${e.substitute} en lugar de ${e.ingredient.name}`).slice(0,3),reason:pantryReason(used.map(i=>i.name),sub.length,issue,index)}}
function pantryReason(p:string[],s:number,i:number,index:number){if(p.length)return`Prioriza ${p.slice(0,2).join(' y ')}, que has marcado para aprovechar.`;if(i===0&&s>0)return'Encaja con lo que tienes gracias a una sustitución culinaria razonable.';if(i===0)return'Aprovecha bien lo disponible sin compras adicionales.';if(i===1)return'Necesita un ajuste pequeño y aprovecha bien el resto.';return['Es una opción coherente aunque requiere completar algunos ingredientes.','Aporta una alternativa distinta equilibrando aprovechamiento, tiempo y dificultad.'][index]??'Opción diferente y razonable.'}
function desireReason(i:number){return['Es la que mejor encaja con lo que has pedido.','Te da una alternativa claramente diferente sin alejarse de tus criterios.'][i]??'Alternativa útil.'}
function textAffinity(recipe:Recipe,q:string){if(!q)return 0;const words=q.split(/\s+/).filter(w=>w.length>3),h=normalize([recipe.title,recipe.description,recipe.cuisine,recipe.style,...recipe.ingredients.map(i=>i.name)].join(' '));return words.filter(w=>h.includes(w)).length}function normalize(v:string){return v.toLocaleLowerCase('es').normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim()}
