import bundledTips from '../public/cooking-tips-v2.json' with {type:'json'};
import {test,expect} from '@playwright/test';
import fs from 'node:fs/promises';
import {cookingTips,nextCookingTip} from '../src/data/cookingTips';
test.beforeEach(async({page})=>{await page.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.abort());await page.addInitScript(()=>{sessionStorage.setItem('chef:auth:session:v1','1');sessionStorage.setItem('chef:entry-tutorial:seen-session:v1','1');sessionStorage.setItem('chef:tutorial:invite-dismissed-session:v2','1')});});
test('tips complete a cycle without repetition',()=>{cookingTips.splice(0,cookingTips.length,...bundledTips as typeof cookingTips);expect(cookingTips).toHaveLength(150);expect(new Set(Array.from({length:150},()=>nextCookingTip()?.id)).size).toBe(150)});
test('tip review persists and searchable catalog displays sources',async({page})=>{await page.goto('./#/consejos');await expect(page.locator('.tip-review-card')).toHaveCount(150);await page.getByLabel('Buscar tip').fill('TIP-001');await expect(page.locator('.tip-review-card')).toHaveCount(1);await page.getByRole('button',{name:'Ocultar',exact:true}).click();await page.reload();await page.getByLabel('Buscar tip').fill('TIP-001');await expect(page.getByRole('button',{name:'Ocultar',exact:true})).toHaveAttribute('aria-pressed','true');await page.getByText('Ver ficha completa',{exact:true}).click();await expect(page.locator('.tip-review-card')).toContainText('Por qué funciona')});
test('loading tips rotate while visible spinner indicates waiting',async({page})=>{await page.clock.install();let release:()=>void=()=>{};await page.route('**/recipes/suggest',async r=>{await new Promise<void>(resolve=>release=resolve);await r.fulfill({status:503,json:{}})});await page.goto('./#/receta/lib-001');await page.getByRole('button',{name:'Crear otra con IA',exact:true}).click();const tip=page.locator('.chef-loading-overlay .cooking-tip p');await expect(tip).toBeVisible();const first=await tip.textContent();await expect(page.locator('.chef-visible-spinner')).toBeVisible();expect(await page.locator('.chef-visible-spinner').evaluate(e=>getComputedStyle(e).animationName)).toBe('chef-progress-spin');expect(await page.locator('.chef-hat-spinner').evaluate(e=>getComputedStyle(e).animationName)).toBe('chef-progress-spin');await page.clock.runFor(9100);await expect(tip).not.toHaveText(first!);release();});
test('source photograph takes precedence and PDF downloads without late JS requests',async({page},info)=>{
 let generated=0;await page.route('**/chef-media/image',r=>{generated++;return r.abort()});await page.goto('./#/consejos');
 await page.evaluate(async()=>{const blob=await(await fetch('./home-photo-recipe.png')).blob();const cache=await caches.open('chef-recipe-source-photos-v1');await cache.put('https://the-chef.local/source-photos/arroz-pollo-calabacin',new Response(blob));});
 await page.goto('./#/receta/arroz-pollo-calabacin');await expect(page.locator('.recipe-complete-photo img')).toBeVisible();expect(generated).toBe(0);
 await expect(page.getByRole('button',{name:'WhatsApp',exact:true})).toHaveCount(0);await expect(page.getByRole('button',{name:'Generar PDF',exact:true})).toHaveCount(0);await expect(page.getByRole('button',{name:'Compartir receta',exact:true})).toHaveCount(1);
 await page.evaluate(()=>Object.defineProperty(navigator,'canShare',{value:()=>false,configurable:true}));await page.route('**/assets/*.js',r=>r.abort());
 const promise=page.waitForEvent('download');await page.getByRole('button',{name:'Compartir receta',exact:true}).click();const download=await promise;const file=info.outputPath('recipe.pdf');await download.saveAs(file);const bytes=await fs.readFile(file);expect(bytes.subarray(0,5).toString()).toBe('%PDF-');expect(bytes.length).toBeGreaterThan(10000);expect(generated).toBe(0);await expect(page.locator('.recipe-share-status')).toContainText('PDF descargado');await page.screenshot({path:info.outputPath('recipe-share.png'),fullPage:true});
});
test('native sharing receives a PDF file and cancellation does not report failure',async({page})=>{await page.addInitScript(()=>{Object.defineProperty(navigator,'canShare',{value:()=>true,configurable:true});Object.defineProperty(navigator,'share',{value:async(data:ShareData)=>{const file=data.files![0];(window as any).shared={name:file.name,type:file.type,size:file.size};throw new DOMException('Cancelado','AbortError')},configurable:true})});await page.goto('./#/receta/arroz-pollo-calabacin');await page.getByRole('button',{name:'Compartir receta',exact:true}).click();await expect.poll(()=>page.evaluate(()=>(window as any).shared)).toMatchObject({type:'application/pdf'});await expect(page.locator('.recipe-share-status')).toHaveCount(0)});

test('catalogs are saved in the local database',async({page})=>{await page.goto('./#/consejos');await expect(page.locator('.tip-review-card')).toHaveCount(150);const counts=await page.evaluate(async()=>{const db=await new Promise<IDBDatabase>((resolve,reject)=>{const r=indexedDB.open('the-chef-culinary-catalog');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});try{return await Promise.all(['techniques','tips'].map(store=>new Promise<number>(resolve=>{const r=db.transaction(store).objectStore(store).count();r.onsuccess=()=>resolve(r.result)})))}finally{db.close()}});expect(counts).toEqual([180,150]);});

test('library PDF includes nutrition and paginates without clipping',async({page},info)=>{
 await page.goto('./#/receta/lib-001?servings=5');await expect(page.locator('.nutrition-card')).toContainText('Por ración');
 await page.evaluate(()=>{Object.defineProperty(navigator,'canShare',{value:()=>false,configurable:true});const original=HTMLCanvasElement.prototype.toDataURL;(window as any).pdfOverflow=[];(window as any).pdfChapters=[];HTMLCanvasElement.prototype.toDataURL=function(...args){(window as any).pdfChapters=Array.from(document.querySelectorAll('.recipe-export-content')).map(el=>({chapter:(el as HTMLElement).dataset.chapter,text:el.textContent}));for(const el of document.querySelectorAll('.recipe-export-content'))(window as any).pdfOverflow.push(el.scrollHeight>el.clientHeight);return original.apply(this,args)}});
 const pending=page.waitForEvent('download');await page.getByRole('button',{name:'Compartir receta',exact:true}).click();const download=await pending;await download.saveAs(info.outputPath('library-recipe.pdf'));
 expect(await page.evaluate(()=>(window as any).pdfOverflow)).not.toContain(true);expect((await page.evaluate(()=>(window as any).pdfOverflow)).length).toBeGreaterThan(0);
 const chapters=await page.evaluate(()=>(window as any).pdfChapters);expect(chapters.map((c:any)=>c.chapter)).toEqual(['cover','ingredients','advice','steps']);expect(chapters[0].text).toContain('Por ración');expect(chapters[1].text).toContain('400 g');expect(chapters[2].text).toContain('Puntos críticos');expect(chapters[3].text).toContain('Paso 4');await expect(page.locator('.recipe-export-host')).toHaveCount(0);
});
