import {test,expect} from '@playwright/test';
import {cookingTips} from '../src/data/cookingTips';
import {techniqueBasics} from '../src/data/techniqueBasics';
test('two isolated devices synchronize reviews and retry offline changes',async({browser})=>{
 test.skip(process.env.CF_PAGES!=='1','Requiere build de preview privada');
 const reviews:Record<string,string>={};let offline=false;
 const first=await browser.newContext(),second=await browser.newContext();
 for(const context of [first,second]){await context.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.abort());await context.route('**/api/session',r=>r.fulfill({json:{user:{id:'access:test',email:'owner@example.test',name:'Mikel',role:'admin'},expiresAt:Date.now()+3600000,stableUrl:null}}));await context.route('**/api/culinary-catalog',r=>{if(offline)return r.abort();if(r.request().method()==='PUT'){const {id,state}=r.request().postDataJSON();if(state==='pending')delete reviews[id];else reviews[id]=state;return r.fulfill({json:{saved:true}})}return r.fulfill({json:{tips:cookingTips,techniques:techniqueBasics,reviews}})});}
 try{const a=await first.newPage(),b=await second.newPage();await a.goto('http://127.0.0.1:4175/#/consejos');await expect(a.getByText('Sincronizado entre dispositivos',{exact:true})).toBeVisible();await a.getByLabel('Buscar consejo').fill('Pesa la harina');await a.getByRole('button',{name:'Ocultar',exact:true}).click();await expect.poll(()=>reviews['tip-1']).toBe('hide');await b.goto('http://127.0.0.1:4175/#/consejos');await expect(b.getByText('Sincronizado entre dispositivos',{exact:true})).toBeVisible();await b.getByLabel('Buscar consejo').fill('Pesa la harina');await expect(b.getByRole('button',{name:'Ocultar',exact:true})).toHaveAttribute('aria-pressed','true');offline=true;await b.getByRole('button',{name:'Me interesa',exact:true}).click();await expect(b.getByText('Guardado aquí; sincronización pendiente',{exact:true})).toBeVisible();expect(reviews['tip-1']).toBe('hide');offline=false;await b.reload();await expect.poll(()=>reviews['tip-1']).toBe('keep');await a.reload();await a.getByLabel('Buscar consejo').fill('Pesa la harina');await expect(a.getByRole('button',{name:'Me interesa',exact:true})).toHaveAttribute('aria-pressed','true');}finally{await first.close();await second.close();}
});
