import {test,expect} from '@playwright/test';
import {publicImportUrl} from '../server/importSource';
import {parseImportText,buildImportedRecipe} from '../src/services/recipeImport';
import {reviewPhotoProposal} from '../src/utils/photoIngredients';
import {jsPDF} from 'jspdf';
const text='Arroz sencillo\nComensales: 2\nIngredientes\n200 g de arroz\n400 ml de agua\nElaboración\n1. Cocer el arroz en el agua.';
test('import parser preserves missing fields and rejects invalid sources',()=>{const d=parseImportText(text);expect(d.servings).toBe('2');expect(d.prep).toBe('');expect(d.ingredients[0]).toEqual({name:'arroz',quantity:'200',unit:'g'});expect(()=>buildImportedRecipe(d)).toThrow();expect(buildImportedRecipe({...d,prep:'0',cook:'20'}).nutritionStatus).toBe('unavailable');for(const url of ['http://example.com','https://127.0.0.1','https://[::1]','https://a.local','https://user:pass@example.com','file:///x'])expect(()=>publicImportUrl(url)).toThrow();for(const url of ['https://www.youtube.com/watch?v=test','https://youtu.be/test','https://m.youtube.com/shorts/test','https://www.youtube-nocookie.com/embed/test'])expect(()=>publicImportUrl(url)).toThrow('YouTube');expect(publicImportUrl('https://example.com/receta').hostname).toBe('example.com');});
test('photo dessert rejects unexplained pantry seasonings but respects explicit user ingredients',()=>{const p={id:'x',recipeId:'x',title:'Tarta tatin con chantilly',subtitle:'Postre',emoji:'🍰',minutes:30,difficulty:'Fácil' as const,reason:'Foto',usedIngredients:['Manzana','Ajo','Pimienta'],missingIngredients:['Nata','Cebolla']};expect(reviewPhotoProposal(p).usedIngredients).toEqual(['Manzana']);expect(reviewPhotoProposal(p).missingIngredients).toEqual(['Nata']);expect(reviewPhotoProposal(p,'Lleva ajo').usedIngredients).toContain('Ajo');});
test.beforeEach(async({page})=>{await page.addInitScript(()=>{for(const k of ['chef:home-greeted:v2','chef:auth:session:v1','chef:entry-tutorial:seen-session:v1','chef:tutorial:invite-dismissed-session:v2'])sessionStorage.setItem(k,'1')});await page.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.abort());});

test('written recipe links still import and YouTube is rejected before a request',async({page})=>{
 let reads=0;
 await page.route('**/api/import-source',r=>{reads++;return r.fulfill({contentType:'application/json',body:JSON.stringify({url:'https://example.com/receta',html:'<script type="application/ld+json">'+JSON.stringify({'@type':'Recipe',name:'Arroz publicado',recipeYield:'2',recipeIngredient:['200 g de arroz','400 ml de agua'],recipeInstructions:[{'@type':'HowToStep',text:'Cocer el arroz en agua durante 20 minutos.'}],author:{name:'Autor de prueba'}})+'</script>'})})});
 await page.goto('./#/importar-receta');
 await page.getByLabel('Enlace de una receta escrita').fill('https://youtu.be/prueba');
 await page.getByRole('button',{name:'Leer enlace',exact:true}).click();
 await expect(page.getByRole('alert')).toContainText('YouTube no está disponible');expect(reads).toBe(0);
 await page.getByLabel('Enlace de una receta escrita').fill('https://example.com/receta');
 await page.getByRole('button',{name:'Leer enlace',exact:true}).click();
 await expect(page.getByLabel('Texto de la receta',{exact:true})).toHaveValue(/Arroz publicado/);expect(reads).toBe(1);
});
test('import text is private, editable and persists with source and unknown nutrition without AI',async({page})=>{let calls=0;await page.route('**/chef-media/**',r=>{calls++;return r.abort()});await page.goto('./#/mis-recetas');await page.getByRole('button',{name:'Importar receta',exact:true}).click();await page.getByLabel('Texto de la receta',{exact:true}).fill(text);await page.getByRole('button',{name:'Organizar sin IA',exact:true}).click();await expect(page.getByRole('button',{name:'Guardar en Mis recetas',exact:true})).toBeDisabled();await page.getByLabel('Preparación (min)',{exact:true}).fill('0');await page.getByLabel('Cocción (min)',{exact:true}).fill('20');await page.getByLabel('Autor o persona',{exact:false}).fill('Receta familiar');await page.getByLabel('Enlace original (opcional)',{exact:true}).fill('https://example.com/arroz');await page.getByRole('checkbox').check();await page.getByRole('button',{name:'Guardar en Mis recetas',exact:true}).click();await expect(page).toHaveURL(/receta\/import-/);await page.reload();await expect(page.getByRole('heading',{name:'Arroz sencillo',exact:true})).toBeVisible();const stored=await page.evaluate(()=>JSON.parse(localStorage.getItem('the-chef:library-recipe-snapshots:v1')!)[0]);expect(stored.source.publisher).toBe('Receta familiar');expect(stored.source.url).toBe('https://example.com/arroz');expect(stored.nutritionStatus).toBe('unavailable');expect(calls).toBe(0);});
test('PDF text extraction loads lazily and does not send the file to AI',async({page})=>{const pdf=new jsPDF();pdf.text(text.split('\n'),20,20);await page.goto('./#/importar-receta');await page.getByLabel('Archivo de receta',{exact:true}).setInputFiles({name:'receta.pdf',mimeType:'application/pdf',buffer:Buffer.from(pdf.output('arraybuffer'))});await expect(page.getByLabel('Texto de la receta',{exact:true})).toHaveValue(/200 g de arroz/,{timeout:30000});await expect(page.getByRole('alert')).toHaveCount(0);});
test('all four social networks offer honest instructions',async({page})=>{await page.goto('./#/receta/lib-001');await page.getByRole('button',{name:'Compartir en redes',exact:true}).click();for(const network of ['Instagram','Facebook','TikTok','X']){await page.getByRole('button',{name:network,exact:true}).click();await expect(page.getByRole('button',{name:network,exact:true})).toHaveAttribute('aria-pressed','true');await expect(page.getByRole('dialog')).toContainText('La publicación se confirma dentro de la red social.');}});

