import {test,expect} from '@playwright/test';
import fs from 'node:fs/promises';
test.beforeEach(async({page})=>{await page.addInitScript(()=>{for(const key of ['chef:auth:session:v1','chef:entry-tutorial:seen-session:v1','chef:tutorial:invite-dismissed-session:v2'])sessionStorage.setItem(key,'1')});await page.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.abort());});
test('post and story download at full resolution with no AI requests',async({page},info)=>{
 let ai=0;await page.route('**/chef-media/image',r=>{ai++;return r.abort()});await page.goto('./#/receta/lib-001?servings=5');await expect(page.getByRole('button',{name:'Compartir PDF',exact:true})).toBeVisible();await page.getByRole('button',{name:'Compartir en redes',exact:true}).click();await expect(page.getByRole('dialog')).toBeVisible();await expect(page.getByAltText('Tarjeta de Paella valenciana')).toBeVisible();await expect(page.getByLabel('Texto para compartir')).toContainText('5 comensales');await expect(page.getByLabel('Texto para compartir')).not.toContainText('#/receta');
 for(const [name,height] of [['Publicación · 4:5',1350],['Historia · 9:16',1920]] as const){await page.getByRole('button',{name,exact:true}).click();await expect(page.getByRole('button',{name:'Descargar imagen',exact:true})).toBeEnabled();const pending=page.waitForEvent('download');await page.getByRole('button',{name:'Descargar imagen',exact:true}).click();const download=await pending;const path=info.outputPath(height+'.png');await download.saveAs(path);const bytes=await fs.readFile(path);expect(bytes.readUInt32BE(16)).toBe(1080);expect(bytes.readUInt32BE(20)).toBe(height);expect(bytes.length).toBeGreaterThan(100000);}
 expect(ai).toBe(0);await page.screenshot({path:info.outputPath('dialog.png')});await page.getByRole('button',{name:'Cerrar compartir en redes',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await expect(page.getByRole('button',{name:'Compartir en redes',exact:true})).toBeFocused();
});
test('native share uses prepared PNG on the user click and cancellation stays quiet',async({page})=>{
 await page.addInitScript(()=>{Object.defineProperty(navigator,'canShare',{configurable:true,value:()=>true});Object.defineProperty(navigator,'share',{configurable:true,value:async(data:ShareData)=>{(window as any).socialShared={type:data.files![0].type,size:data.files![0].size,text:data.text,active:navigator.userActivation.isActive};throw new DOMException('Cancelado','AbortError');}})});
 await page.goto('./#/receta/lib-002');await page.getByRole('button',{name:'Compartir en redes',exact:true}).click();const share=page.getByRole('button',{name:'Compartir imagen',exact:true});await expect(share).toBeEnabled();await share.click();await expect.poll(()=>page.evaluate(()=>(window as any).socialShared)).toMatchObject({type:'image/png',active:true});await expect(page.getByRole('dialog')).not.toContainText('No se ha podido');await expect(page.getByRole('dialog')).not.toContainText('Imagen descargada');
});
test('unsupported native file share downloads instead and supports copying caption',async({page})=>{
 await page.addInitScript(()=>{Object.defineProperty(navigator,'canShare',{configurable:true,value:()=>false});Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async(text:string)=>{(window as any).copiedCaption=text;}}});});
 await page.goto('./#/receta/lib-003');await page.getByRole('button',{name:'Compartir en redes',exact:true}).click();await expect(page.getByRole('button',{name:'Compartir imagen',exact:true})).toBeEnabled();const pending=page.waitForEvent('download');await page.getByRole('button',{name:'Compartir imagen',exact:true}).click();expect((await pending).suggestedFilename()).toMatch(/publicacion-the-chef\.png$/);await page.getByRole('button',{name:'Copiar texto y enlace',exact:true}).click();await expect.poll(()=>page.evaluate(()=>(window as any).copiedCaption)).toContain('Arroz negro');await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toHaveCount(0);
});
test('native failure offers download without claiming a publication',async({page})=>{
 await page.addInitScript(()=>{Object.defineProperty(navigator,'canShare',{configurable:true,value:()=>true});Object.defineProperty(navigator,'share',{configurable:true,value:async()=>{throw new DOMException('Blocked','NotAllowedError');}})});await page.goto('./#/receta/lib-001');await page.getByRole('button',{name:'Compartir en redes',exact:true}).click();await expect(page.getByRole('button',{name:'Compartir imagen',exact:true})).toBeEnabled();await page.getByRole('button',{name:'Compartir imagen',exact:true}).click();await expect(page.getByRole('dialog')).toContainText('Puedes descargar la imagen');await expect(page.getByRole('button',{name:'Descargar imagen',exact:true})).toBeEnabled();
});
