import { Check, ChevronLeft, ChevronRight, Mic, PenLine, Sparkles } from 'lucide-react';
import { useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useApp } from '../AppContext';
import { AppShell } from '../components/AppShell';
import { ChefLoadingOverlay } from '../components/ChefLoadingOverlay';
import { Chip } from '../components/Chip';
import { CuisineSelect } from '../components/CuisineSelect';
import { NumberStepper } from '../components/NumberStepper';
import { PrimaryButton } from '../components/PrimaryButton';
import { TopBar } from '../components/TopBar';
import { RECIPE_STYLES } from '../data/cookingOptions';
import type { CookingRequest, Recipe } from '../domain/types';
import { useAiDictation } from '../hooks/useAiDictation';
import { fetchAiProposals, generateAiRecipe } from '../services/aiProposalGateway';
import { registerExternalRecipes, rememberActiveRecipe, rememberLibraryRecipe } from '../services/recipeCatalog';
import '../voice-input.css';

type Stage='basic'|'ingredients'|'mise'|'recommendations'|'critical'|'elaboration'|'validate'|'review';
const ORDER:Stage[]=['basic','ingredients','mise','recommendations','critical','elaboration','validate','review'];

export function CreateRecipePage(){
 const navigate=useNavigate(); const {settings,toggleSavedRecipe,savedRecipes}=useApp();
 const [stage,setStage]=useState<Stage>('basic'); const [title,setTitle]=useState(''); const [style,setStyle]=useState<string>('Casera'); const [cuisine,setCuisine]=useState<string>(); const [servings,setServings]=useState(settings.defaultServings);
 const [ingredients,setIngredients]=useState(''); const [mise,setMise]=useState(''); const [recommendations,setRecommendations]=useState(''); const [critical,setCritical]=useState(''); const [elaboration,setElaboration]=useState(''); const [draft,setDraft]=useState<Recipe>(); const [stepIndex,setStepIndex]=useState(0); const [stepEdit,setStepEdit]=useState(''); const [working,setWorking]=useState(false); const [error,setError]=useState<string>();
 const activeText=stage==='ingredients'?ingredients:stage==='mise'?mise:stage==='recommendations'?recommendations:stage==='critical'?critical:elaboration;
 const setActiveText=(v:string)=>{if(stage==='ingredients')setIngredients(v);else if(stage==='mise')setMise(v);else if(stage==='recommendations')setRecommendations(v);else if(stage==='critical')setCritical(v);else setElaboration(v)};
 const voice=useAiDictation(t=>setActiveText(activeText.trim()?`${activeText.trim()} ${t.trim()}`:t.trim()));
 const index=ORDER.indexOf(stage); const canNext=stage==='basic'?Boolean(title.trim()):stage==='ingredients'?Boolean(ingredients.trim()):stage==='elaboration'?Boolean(elaboration.trim()):true;
 const next=()=>setStage(ORDER[Math.min(ORDER.length-1,index+1)]); const back=()=>setStage(ORDER[Math.max(0,index-1)]);
 const prompt=useMemo(()=>`Quiero documentar una receta propia llamada “${title.trim()}”. Estilo: ${style}. Cocina: ${cuisine||'sin especificar'}. Comensales: ${servings}. Ingredientes que uso: ${ingredients}. Mise en place que hago: ${mise||'no indicada'}. Recomendaciones personales: ${recommendations||'ninguna indicada'}. Puntos críticos que conozco: ${critical||'ninguno indicado'}. Elaboración contada por mí: ${elaboration}. Respeta mi receta y mi intención. Estructúrala con cantidades coherentes para ${servings} comensales, pasos cronológicos, tiempos, temperaturas y señales de avance solo cuando sean culinariamente justificables. Conserva mis consejos si son correctos y mejora únicamente lo que aporte una mejora sustancial.`,[title,style,cuisine,servings,ingredients,mise,recommendations,critical,elaboration]);
 const generate=async()=>{if(working||!elaboration.trim())return;setWorking(true);setError(undefined);try{const request:CookingRequest={mode:'desire',servings,maxMinutes:120,style,cuisine,desireText:prompt,aiPreference:100,pantryPolicy:'ignore'};const proposals=await fetchAiProposals(request);if(!proposals[0])throw new Error('La IA no ha podido estructurar esta receta.');const generated=await generateAiRecipe(request,proposals[0]);const own:Recipe={...generated,id:`user-${Date.now()}`,title:title.trim(),baseServings:servings,source:{kind:'user',label:'Receta creada por el usuario',adapted:true}};setDraft(own);setStepIndex(0);setStepEdit(own.steps[0]?.instruction??'');setStage('validate')}catch(e){setError(e instanceof Error?e.message:'No se ha podido estructurar la receta.')}finally{setWorking(false)}};
 const validateStep=()=>{if(!draft)return;const steps=draft.steps.map((s,i)=>i===stepIndex?{...s,instruction:stepEdit.trim()||s.instruction}:s);const nextDraft={...draft,steps};setDraft(nextDraft);if(stepIndex<steps.length-1){const ni=stepIndex+1;setStepIndex(ni);setStepEdit(steps[ni].instruction)}else setStage('review')};
 const save=()=>{if(!draft)return;const [stored]=registerExternalRecipes([draft]);if(!stored){setError('La receta no ha superado la validación final.');return}rememberActiveRecipe(stored);rememberLibraryRecipe(stored);if(!savedRecipes.includes(stored.id))toggleSavedRecipe(stored.id);navigate(`/receta/${stored.id}`)};
 return <AppShell><ChefLoadingOverlay active={working} title="Dando forma a tu receta" messages={['¡Oído cocina!','Organizando tus ingredientes…','Revisando la mise en place…','Ordenando la elaboración…','Comprobando puntos críticos…']}/><TopBar eyebrow="TU RECETA" title="Crear tu receta"/><div className="page-content nav-safe">
  {stage==='basic'&&<section className="editorial-card olive-intro"><PenLine size={25}/><h2>Empezamos por lo esencial.</h2><label className="settings-user-fields"><span>Título de la receta</span><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Ej. Calamares de la abuela"/></label><div className="advanced-group"><strong>Estilo</strong><div className="chip-row">{RECIPE_STYLES.map(v=><Chip key={v} selected={style===v} onClick={()=>setStyle(v)}>{v}</Chip>)}</div></div><div className="advanced-group"><strong>Tipo de cocina</strong><CuisineSelect value={cuisine} onChange={setCuisine}/></div><div className="control-row"><div><strong>Comensales</strong></div><NumberStepper value={servings} onChange={setServings}/></div></section>}
  {(['ingredients','mise','recommendations','critical','elaboration'] as Stage[]).includes(stage)&&<section className="editorial-card"><span className="eyebrow">PASO {index+1} DE 6</span><h2>{stage==='ingredients'?'¿Qué ingredientes utilizas?':stage==='mise'?'¿Qué mise en place haces?':stage==='recommendations'?'¿Qué recomendaciones das siempre?':stage==='critical'?'¿Qué puntos críticos hay?':'Cuéntame cómo haces la elaboración'}</h2><p>{stage==='ingredients'?'Nómbralos; no hace falta que conozcas todas las cantidades.':stage==='mise'?'Descríbela con tus palabras. Si ya está bien, The Chef la respetará.':stage==='recommendations'?'Tus trucos de siempre. Déjalo vacío si no hay ninguno.':stage==='critical'?'Esos detalles que evitan que la receta salga mal.':'Cuéntala como se la contarías a otra persona. The Chef la convertirá después en pasos reproducibles.'}</p><textarea rows={stage==='elaboration'?9:6} value={activeText} onChange={e=>setActiveText(e.target.value)} placeholder="Escribe o dicta aquí…"/><button type="button" className={`voice-button ${voice.isListening?'listening':''}`} onClick={voice.toggle} disabled={!voice.isSupported||voice.isTranscribing}><Mic size={19}/></button>{voice.isListening&&<div className="voice-status listening">Escuchando…</div>}</section>}
  {stage==='elaboration'&&<PrimaryButton onClick={()=>void generate()} disabled={!elaboration.trim()||working}>{working?'Estructurando…':'Preparar propuesta de receta'}</PrimaryButton>}
  {stage==='validate'&&draft&&<section className="editorial-card"><span className="eyebrow">VALIDACIÓN DE ELABORACIÓN</span><h2>Paso {stepIndex+1} de {draft.steps.length}</h2><p>Revísalo y corrige el texto si quieres. Al validar pasaremos al siguiente.</p><textarea rows={7} value={stepEdit} onChange={e=>setStepEdit(e.target.value)}/><div className="pantry-basics-note">{draft.steps[stepIndex]?.minutes?`${draft.steps[stepIndex].minutes} min`:''}{draft.steps[stepIndex]?.temperatureC?` · ${draft.steps[stepIndex].temperatureC} °C`:''}{draft.steps[stepIndex]?.cue?` · Fíjate: ${draft.steps[stepIndex].cue}`:''}</div><PrimaryButton onClick={validateStep}><Check size={18}/> Validar paso</PrimaryButton></section>}
  {stage==='review'&&draft&&<section className="editorial-card olive-intro"><Sparkles size={25}/><h2>Tu receta está lista para revisar.</h2><p><strong>{draft.title}</strong></p><p>{draft.description}</p><div className="pantry-basics-note">{draft.ingredients.length} ingredientes · {draft.steps.length} pasos · {draft.prepMinutes+draft.cookMinutes} min</div><PrimaryButton onClick={save}>Guardar y abrir receta</PrimaryButton></section>}
  {error&&<div className="voice-status error">{error}</div>}
  {stage!=='validate'&&stage!=='review'&&stage!=='elaboration'&&<div style={{display:'flex',gap:10,marginTop:16}}>{index>0&&<button type="button" className="secondary-button" onClick={back}><ChevronLeft size={18}/>Atrás</button>}<button type="button" className="secondary-button" disabled={!canNext} onClick={next}>Continuar<ChevronRight size={18}/></button></div>}
 </div></AppShell>
}
