import {generatePlanMeal,percentageMacros,planNutrition} from '../services/aiMealPlan';
import {useEffect,useRef,useState} from 'react';
import {Link} from 'react-router-dom';
import {CalendarDays,ShieldCheck,Calculator,ShoppingBasket} from 'lucide-react';
import {AppShell} from '../components/AppShell';
import {useApp} from '../AppContext';
import {getAllRecipes} from '../services/recipeCatalog';
import {libraryImage} from '../data/library';
import {planBreakfasts} from '../data/planBreakfasts';
import {CUISINES,RECIPE_STYLES} from '../data/cookingOptions';


import {scaleQuantity,formatQuantity} from '../utils/scaling';
import {ACTIVITY,ALLERGENS,MEALS,NUTRIENTS,chooseRecipe,emptyData,estimateMaintenance,makePlan,planShopping,sumNutrition,unknownNutrition,validateWeight,validateOptions,type Plan,type Goal,type Meal,type Nutrients,type PlanOptions,type PlanSlot} from '../services/mealPlan';
import {decryptPlan,downloadPlan,encryptPlan,setPlanData,usePlanData} from '../services/mealPlanSession';
import './MealPlanPage.css';

const labels={kcal:'kcal',proteinG:'g proteína',carbsG:'g hidratos',fatG:'g grasas',fiberG:'g fibra'};
function Nutrition({value}:{value:Nutrients}){return <div className="plan-nutrition">{NUTRIENTS.map(k=><span key={k}><strong>{value[k]===null?'Sin datos':Math.round(value[k]!)}</strong><small>{labels[k]}</small></span>)}</div>}
const numberOrUndefined=(value:string)=>value.trim()===''?undefined:Number(value);
export function MealPlanPage(){
 const data=usePlanData(),{settings,favorites,savedRecipes,replacePlanShopping}=useApp();
 const p=data.plan,initial=p?.options;
 const [weeks,setWeeks]=useState(initial?.weeks??1),[servings,setServings]=useState(initial?.servings??settings.defaultServings);
 const [meals,setMeals]=useState<Meal[]>(initial?.meals??['Comida','Cena']);
 const [shares,setShares]=useState(initial?.shares??{Desayuno:0,Comida:0,Merienda:0,Cena:0});
 const [mode,setMode]=useState(initial?.goal?'goal':'none'),[kcal,setKcal]=useState(initial?.goal?.kcal.toString()??'');
 const [origin,setOrigin]=useState(initial?.goal?.origin??'Lo he decidido yo'),[confirmed,setConfirmed]=useState<Goal|undefined>(initial?.goal);
 const [macros,setMacros]=useState({proteinG:initial?.goal?.proteinG?.toString()??'',carbsG:initial?.goal?.carbsG?.toString()??'',fatG:initial?.goal?.fatG?.toString()??''});
 const [restrictions,setRestrictions]=useState(initial?.restrictions.filter(r=>ALLERGENS.includes(r)||['Vegetariana','Vegana'].includes(r))??[]);
 const [excluded,setExcluded]=useState(initial?.restrictions.filter(r=>!ALLERGENS.includes(r)&&!['Vegetariana','Vegana'].includes(r)).join(', ')??'');
 const [cuisine,setCuisine]=useState(initial?.cuisine??''),[style,setStyle]=useState(initial?.style??''),[likes,setLikes]=useState(initial?.likes??''),[minutes,setMinutes]=useState(initial?.maxMinutes?.toString()??'');
 const [planEngine,setPlanEngine]=useState('ai'),[macroMode,setMacroMode]=useState(initial?.goal?.proteinG!==undefined?'grams':'auto'),[percent,setPercent]=useState({protein:'',carbs:'',fat:''}),[fiber,setFiber]=useState(initial?.goal?.fiberG?.toString()??'');
 const stopGeneration=useRef(false);
 const [changes,setChanges]=useState<Record<string,string>>({}),[candidate,setCandidate]=useState<{slot:PlanSlot;recipe:import('../domain/types').Recipe}>();
 const [prefer,setPrefer]=useState(initial?.preferred.length?'saved':'all');
 const [error,setError]=useState(''),[status,setStatus]=useState(''),[week,setWeek]=useState(0),[busy,setBusy]=useState(false);
 const [personal,setPersonal]=useState({weight:'',height:'',age:'',sex:'female',activity:0,eligible:false});
 const [date,setDate]=useState(new Date().toISOString().slice(0,10)),[weight,setWeight]=useState(''),[weightConsent,setWeightConsent]=useState(false);
 const [password,setPassword]=useState(''),[passwordRepeat,setPasswordRepeat]=useState(''),[file,setFile]=useState<File>(),[subtract,setSubtract]=useState(false),[aiConsent,setAiConsent]=useState(false),[deleteConfirm,setDeleteConfirm]=useState(false);
 const alive=useRef(true);useEffect(()=>{alive.current=true;return()=>{alive.current=false}},[]);
 const catalog=()=>[...getAllRecipes(),...planBreakfasts];
 const run=(fn:()=>void)=>{setError('');setStatus('');try{fn()}catch(e){setError(e instanceof Error?e.message:'No se ha podido completar la acción.')}};
 const options=():PlanOptions=>({weeks,servings,meals,shares,goal:mode==='goal'?confirmed:undefined,restrictions:[...restrictions,...excluded.split(/[,;]+/).map(s=>s.trim()).filter(Boolean)],cuisine,style,likes,maxMinutes:numberOrUndefined(minutes),preferred:prefer==='saved'?[...new Set([...favorites,...savedRecipes])]:[]});
 async function generate(){if(planEngine==='library'){run(()=>{if(mode==='goal'&&!confirmed)throw Error('Confirma expresamente tu objetivo antes de crear el plan.');setPlanData({...data,plan:makePlan(options(),catalog())});setWeek(0);setStatus('Plan de biblioteca creado.');});return;}if(busy)return;setError('');if(!aiConsent){setError('Autoriza el uso de IA antes de generar el plan.');return;}setBusy(true);setCandidate(undefined);stopGeneration.current=false;try{if(mode==='goal'&&!confirmed)throw Error('Confirma expresamente tu objetivo antes de crear el plan.');const o=options();validateOptions(o);const plan:Plan={options:structuredClone(o),slots:Array.from({length:o.weeks*7},(_,day)=>o.meals.map(meal=>({day,meal}))).flat(),createdAt:new Date().toISOString()};setWeek(0);for(let i=0;i<plan.slots.length;i++){if(stopGeneration.current||!alive.current)break;const slot=plan.slots[i];setStatus(`Generando comida ${i+1} de ${plan.slots.length} con IA…`);slot.recipe=await generatePlanMeal(o,slot.meal,plan.slots.flatMap(s=>s.recipe?[s.recipe.title]:[]),settings.language);if(!alive.current)break;setPlanData({...data,plan:structuredClone(plan)});}if(alive.current)setStatus(stopGeneration.current?'Generación detenida. Se conservan las comidas completadas.':'Propuesta generada con IA. Revisa comidas y diferencias respecto al objetivo antes de utilizarla.');}catch(e){if(alive.current)setError(e instanceof Error?e.message:'No se ha podido generar el plan. Se conservan las comidas completadas.');}finally{if(alive.current)setBusy(false);}}
 function confirmGoal(){run(()=>{if(macroMode==='percent'&&Object.values(percent).some(v=>v.trim()===''))throw Error('Completa los tres porcentajes.');const goal={kcal:Number(kcal),origin,confirmedAt:new Date().toISOString(),...(macroMode==='percent'?percentageMacros(Number(kcal),Number(percent.protein),Number(percent.carbs),Number(percent.fat)):macroMode==='grams'?{proteinG:numberOrUndefined(macros.proteinG),carbsG:numberOrUndefined(macros.carbsG),fatG:numberOrUndefined(macros.fatG)}:{}),fiberG:numberOrUndefined(fiber)};if(fiber!==''&&(!Number.isFinite(Number(fiber))||Number(fiber)<0))throw Error('Revisa la fibra en gramos diarios.');if(!kcal||!Number.isFinite(goal.kcal)||goal.kcal<=0)throw Error('Introduce un objetivo positivo en kcal/día.');if(Object.values(macros).some(v=>v!==''&&(!Number.isFinite(Number(v))||Number(v)<0)))throw Error('Revisa los macros.');setConfirmed(goal);setStatus('Objetivo confirmado por ti. Se aplicará al crear el plan.');});}
 function replace(slot:PlanSlot){if(!p)return;run(()=>{const recipe=chooseRecipe(catalog(),p.options,slot.meal,p.slots.flatMap(s=>s.recipe?[s.recipe.id]:[]),slot.recipe?.id);if(!recipe)throw Error('No hay otra receta compatible en la biblioteca. Puedes solicitar una alternativa con IA.');setPlanData({...data,plan:{...p,slots:p.slots.map(s=>s===slot?{...s,recipe}:s)}});setStatus('Comida sustituida. Actualiza la lista de compra si ya la habías enviado.');});}
 async function generateAlternative(slot:PlanSlot){if(!p||busy)return;setError('');setStatus('');if(!aiConsent){setError('Autoriza el envío de las preferencias culinarias antes de utilizar IA.');return;}setBusy(true);
  try{
   const recipe=await generatePlanMeal(p.options,slot.meal,p.slots.flatMap(s=>s.recipe?[s.recipe.title]:[]),settings.language,changes[slot.day+':'+slot.meal]||'',slot.recipe);if(!alive.current)return;setCandidate({slot,recipe});setStatus('Alternativa preparada. Revisa la propuesta y confirma si quieres sustituir la comida.');
  }catch(e){if(alive.current)setError(e instanceof Error?e.message:'No se ha podido generar la alternativa.');}finally{if(alive.current)setBusy(false)}
 }
 async function backup(restore:boolean){setError('');setStatus('');setBusy(true);try{if(restore){if(!file)throw Error('Selecciona una copia cifrada.');if(file.size>10_000_000)throw Error('Archivo demasiado grande.');const imported=await decryptPlan(await file.text(),password);setPlanData(imported);const o=imported.plan?.options;if(o){setWeeks(o.weeks);setServings(o.servings);setMeals(o.meals);setShares(o.shares);setMode(o.goal?'goal':'none');setKcal(o.goal?.kcal.toString()??'');setConfirmed(o.goal);setMacroMode(o.goal?.proteinG!==undefined?'grams':'auto');setFiber(o.goal?.fiberG?.toString()??'');setOrigin(o.goal?.origin??'Lo he decidido yo');setMacros({proteinG:o.goal?.proteinG?.toString()??'',carbsG:o.goal?.carbsG?.toString()??'',fatG:o.goal?.fatG?.toString()??''});setRestrictions(o.restrictions.filter(r=>ALLERGENS.includes(r)||['Vegetariana','Vegana'].includes(r)));setExcluded(o.restrictions.filter(r=>!ALLERGENS.includes(r)&&!['Vegetariana','Vegana'].includes(r)).join(', '));setCuisine(o.cuisine);setStyle(o.style);setLikes(o.likes);setMinutes(o.maxMinutes?.toString()??'');setPrefer(o.preferred.length?'saved':'all');}setStatus('Copia recuperada. El plan anterior de esta sesión se ha sustituido.');setWeek(0);}else{if(password!==passwordRepeat)throw Error('Las contraseñas no coinciden.');downloadPlan(await encryptPlan(data,password));setStatus('Copia cifrada descargada. Guarda la contraseña por separado.');}setPassword('');setPasswordRepeat('');}catch(e){setError(e instanceof Error?e.message:'No se ha podido procesar la copia.');}finally{setBusy(false)}}
 const weights=[...data.weights].sort((a,b)=>a.date.localeCompare(b.date)),values=weights.map(w=>w.kg),min=Math.min(...values),max=Math.max(...values);
 const points=weights.map((w,i)=>`${20+(weights.length===1?130:i*260/(weights.length-1))},${100-(w.kg-min)/(max-min||1)*80}`).join(' ');
 const coverage=p?.options.goal?p.options.meals.reduce((s,m)=>s+p.options.shares[m],0):0;
 return <AppShell><div className="page-content nav-safe meal-plan-page">
  <section className="editorial-card olive-intro"><CalendarDays/><h1>Mi plan de comidas</h1><p>Tú eliges el objetivo. La IA propone tu plan de comidas.</p><p>Planifica de una a cuatro semanas, también sin contar calorías.</p><small>Para conservar tus datos al cerrar, guarda una copia cifrada.</small></section>
  <details className="settings-card"><summary><ShieldCheck size={18}/> Tus datos, bajo tu control</summary><p>El plan y el peso permanecen en esta sesión y se pierden al recargar o cerrar. Para conservarlos, descarga una copia cifrada y recupérala con tu contraseña. No se sincronizan con una cuenta.</p><p>No es una prescripción nutricional. La validación profesional y jurídica para comercializar el módulo está pendiente.</p></details>
  <details className="settings-card" open={!p}><summary>Preparar o cambiar mi plan</summary><div className="plan-stack">
   <label>Cómo generar el plan<select aria-label="Cómo generar el plan" value={planEngine} onChange={e=>setPlanEngine(e.target.value)}><option value="ai">Plan con IA</option><option value="library">Biblioteca · sin IA</option></select></label><p>El plan con IA está disponible en esta preview. La modalidad de pago futura todavía no está activada.</p>
   <label>Duración<select aria-label="Duración" value={weeks} onChange={e=>setWeeks(Number(e.target.value))}>{[1,2,3,4].map(n=><option key={n} value={n}>{n} {n===1?'semana':'semanas'}</option>)}</select></label>
   <label>Comensales<select aria-label="Comensales" value={servings} onChange={e=>setServings(Number(e.target.value))}>{Array.from({length:24},(_,i)=><option key={i+1}>{i+1}</option>)}</select></label>
   <fieldset><legend>Comidas que quiero planificar</legend><div className="plan-checks">{MEALS.map(m=><label key={m}><input type="checkbox" checked={meals.includes(m)} onChange={e=>setMeals(MEALS.filter(v=>v===m?e.target.checked:meals.includes(v)))}/>{m}</label>)}</div></fieldset>
   <label>Objetivo energético<select aria-label="Objetivo energético" value={mode} onChange={e=>setMode(e.target.value)}><option value="none">No lo sé / No quiero establecer un objetivo</option><option value="goal">Quiero introducir mi objetivo</option></select></label>
   {mode==='goal'&&<section className="plan-stack plan-inset">
    <details><summary><Calculator size={18}/> Calcular mantenimiento estimado (opcional)</summary><div className="plan-stack"><p>Solo para adultos de 19–78 años dentro del ámbito de la ecuación. No se aplica a embarazo, lactancia, bajo peso, enfermedad, trastornos alimentarios ni deportistas de élite. Puedes continuar sin calculadora.</p>
     <div className="plan-grid">{([['weight','Peso (kg)'],['height','Altura (cm)'],['age','Edad (años)']] as const).map(([key,label])=><label key={key}>{label}<input type="number" min="0" value={personal[key]} onChange={e=>setPersonal({...personal,[key]:e.target.value})}/></label>)}</div>
     <label>Sexo utilizado por la ecuación<select aria-label="Sexo utilizado por la ecuación" value={personal.sex} onChange={e=>setPersonal({...personal,sex:e.target.value})}><option value="female">Femenino</option><option value="male">Masculino</option></select></label>
     <label>Actividad habitual, incluido el ejercicio<select aria-label="Actividad habitual, incluido el ejercicio" value={personal.activity} onChange={e=>setPersonal({...personal,activity:Number(e.target.value)})}>{ACTIVITY.map((a,i)=><option key={a.label} value={i}>{a.label}</option>)}</select></label>
     <label className="plan-check"><input type="checkbox" checked={personal.eligible} onChange={e=>setPersonal({...personal,eligible:e.target.checked})}/>He leído el ámbito de uso y no estoy en esas situaciones especiales.</label>
     <button className="secondary-button" disabled={busy} onClick={()=>run(()=>{setPlanData({...data,maintenance:estimateMaintenance(Number(personal.weight),Number(personal.height),Number(personal.age),personal.sex as 'female'|'male',personal.activity,personal.eligible)});setPersonal({weight:'',height:'',age:'',sex:'female',activity:0,eligible:false});})}>Calcular estimación</button>
    </div></details>
    {data.maintenance&&<div className="plan-inset"><h3>Calorías de mantenimiento estimadas</h3><strong>{data.maintenance.low}–{data.maintenance.high} kcal/día</strong><p>Reposo estimado: {data.maintenance.rest} kcal/día.</p><p>Calculadas a partir de tus datos y actividad. Son una estimación orientativa, no una prescripción nutricional.</p><small>{data.maintenance.method}</small></div>}
    <label>Mi objetivo (kcal/día por persona)<input type="number" min="1" value={kcal} onChange={e=>{setKcal(e.target.value);setConfirmed(undefined)}}/></label>
    <label>Origen del objetivo<select aria-label="Origen del objetivo" value={origin} onChange={e=>{setOrigin(e.target.value);setConfirmed(undefined)}}>{['Lo he decidido yo','Me lo ha indicado un profesional','Otro'].map(v=><option key={v}>{v}</option>)}</select></label>
    <label>Distribución de nutrientes<select aria-label="Distribución de nutrientes" value={macroMode} onChange={e=>{setMacroMode(e.target.value);setConfirmed(undefined)}}><option value="auto">Que la IA proponga la distribución</option><option value="percent">Introducir porcentajes</option><option value="grams">Introducir gramos diarios</option></select></label>
    {macroMode==='percent'&&<div className="plan-grid">{([['protein','Proteínas'],['carbs','Hidratos'],['fat','Grasas']] as const).map(([key,label])=><label key={key}>{label} (%)<input type="number" min="0" max="100" value={percent[key]} onChange={e=>{setPercent({...percent,[key]:e.target.value});setConfirmed(undefined)}}/></label>)}<p>Los tres porcentajes deben sumar 100 %.</p></div>}
    {macroMode==='grams'&&<div className="plan-grid">{(['proteinG','carbsG','fatG'] as const).map(k=><label key={k}>{labels[k]} / día<input type="number" min="0" value={macros[k]} onChange={e=>{setMacros({...macros,[k]:e.target.value});setConfirmed(undefined)}}/></label>)}</div>}
    <label>Fibra (g/día, opcional)<input type="number" min="0" value={fiber} onChange={e=>{setFiber(e.target.value);setConfirmed(undefined)}}/></label>
    <p>La cifra es una elección tuya; la app no determina si es adecuada o segura para ti.</p><button className="secondary-button" onClick={confirmGoal}>Confirmar mi objetivo</button>{confirmed&&<p>Confirmado: {confirmed.kcal} kcal/día · {confirmed.origin}</p>}
    <fieldset><legend>Reparto elegido por ti (% del objetivo diario)</legend><p>No hay reparto recomendado por defecto. Si planificas solo parte del día, deja el resto sin asignar.</p><div className="plan-grid">{meals.map(m=><label key={m}>{m} (%)<input type="number" min="1" max="100" value={shares[m]||''} onChange={e=>setShares({...shares,[m]:Number(e.target.value)})}/></label>)}</div><p>Asignado: {meals.reduce((s,m)=>s+shares[m],0)} %</p></fieldset>
   </section>}
   <label>Gustos culinarios (preferencia, no obligación)<input value={likes} onChange={e=>setLikes(e.target.value)} placeholder="Ej. arroz"/></label>
   <label>Tipo de cocina<select aria-label="Tipo de cocina" value={cuisine} onChange={e=>setCuisine(e.target.value)}><option value="">Indiferente</option>{CUISINES.map(c=><option key={c}>{c}</option>)}</select></label>
   <label>Estilo<select aria-label="Estilo" value={style} onChange={e=>setStyle(e.target.value)}><option value="">Indiferente</option>{RECIPE_STYLES.filter(v=>v!=='Indiferente').map(v=><option key={v}>{v}</option>)}</select></label>
   <label>Tiempo máximo por receta (minutos, opcional)<input type="number" min="1" value={minutes} onChange={e=>setMinutes(e.target.value)}/></label>
   <fieldset><legend>Alergias y preferencias declaradas</legend><p>Se excluyen ingredientes identificados y algunos compuestos sin composición completa. Comprueba siempre etiquetas y trazas: no podemos certificar que un plato esté libre de alérgenos.</p><div className="plan-checks">{[...ALLERGENS,'Vegetariana','Vegana'].map(a=><label key={a}><input type="checkbox" checked={restrictions.includes(a)} onChange={e=>setRestrictions(e.target.checked?[...restrictions,a]:restrictions.filter(v=>v!==a))}/>{a}</label>)}</div></fieldset>
   <label>Otros alimentos excluidos (separados por comas)<input value={excluded} onChange={e=>setExcluded(e.target.value)} placeholder="Ej. cebolla, ajo"/></label>
   <label>Preferencia de biblioteca<select aria-label="Preferencia de biblioteca" value={prefer} onChange={e=>setPrefer(e.target.value)}><option value="all">Toda la biblioteca</option><option value="saved">Priorizar guardadas y favoritas</option></select></label>
   {planEngine==='ai'&&<><p>Se hará una petición por comida: {weeks*7*meals.length} peticiones para este plan. No se generan imágenes. Puedes detenerlo; la petición en curso puede terminar.</p><label className="plan-check"><input type="checkbox" checked={aiConsent} onChange={e=>setAiConsent(e.target.checked)}/>Autorizo enviar objetivo calórico, macros elegidos, gustos, exclusiones y comensales al servicio de IA para este plan. No se envían peso, edad ni historial.</label></>}<button className="primary-button" disabled={busy} onClick={()=>void generate()}>Crear plan de comidas</button>{busy&&<button className="secondary-button" onClick={()=>{stopGeneration.current=true;setStatus('Se detendrá tras la petición en curso.');}}>Detener generación</button>}{p&&<small>Los cambios del formulario se aplican al pulsar Crear plan de comidas. El plan anterior se sustituye en esta sesión.</small>}
  </div></details>
  {error&&<p role="alert" className="plan-message">{error}</p>}{status&&<p role="status" className="plan-message">{status}</p>}{busy&&<p role="status">Preparando…</p>}
  {p&&<>
   <section className="settings-card"><h2>Tu plan · {p.options.weeks} {p.options.weeks===1?'semana':'semanas'}</h2><p>{p.options.servings} comensales · valores por persona.</p>{p.options.goal?<><p>Objetivo elegido: <strong>{p.options.goal.kcal} kcal/día</strong> · {p.options.goal.origin}. Confirmado el {new Date(p.options.goal.confirmedAt).toLocaleDateString('es-ES')}.</p><p>Planificas el {coverage} %: {Math.round(p.options.goal.kcal*coverage/100)} kcal/día. El resto ({Math.round(p.options.goal.kcal*(100-coverage)/100)} kcal) no está organizado aquí.</p>{data.maintenance&&<p>Diferencia seleccionada respecto al intervalo de mantenimiento: {Math.round(p.options.goal.kcal-data.maintenance.high)} a {Math.round(p.options.goal.kcal-data.maintenance.low)} kcal/día. No predice cambios de peso.</p>}</>:<p>Sin objetivo energético. Menú culinario, no dieta personalizada.</p>}<p>Las cantidades y valores nutricionales son estimaciones. Revisa las diferencias respecto al objetivo: no se garantiza su cumplimiento exacto.</p>
   <label>Semana<select aria-label="Semana" value={week} onChange={e=>setWeek(Number(e.target.value))}>{Array.from({length:p.options.weeks},(_,i)=><option key={i} value={i}>Semana {i+1}</option>)}</select></label></section>
   {Array.from({length:7},(_,d)=>week*7+d).map(day=>{const slots=p.slots.filter(s=>s.day===day),total=sumNutrition(slots.map(s=>s.recipe?planNutrition(s.recipe,p.options.servings):unknownNutrition()));return <section className="settings-card plan-day" key={day}><h2>Día {day+1}</h2>{slots.map(slot=><article className="plan-meal" key={slot.meal}><h3>{slot.meal}</h3>{slot.recipe?<><div className="plan-recipe-title">{libraryImage(slot.recipe.id,true)&&<img loading="lazy" src={libraryImage(slot.recipe.id,true)} alt=""/>}<strong>{slot.recipe.title}</strong></div><Nutrition value={planNutrition(slot.recipe,p.options.servings)}/>{slot.recipe.source?.kind==='ai'&&<small>Valores orientativos: calculados con ingredientes conocidos o estimados por IA cuando faltan datos.</small>}{p.options.goal&&<small>Asignado: {Math.round(p.options.goal.kcal*p.options.shares[slot.meal]/100)} kcal · diferencia: {planNutrition(slot.recipe,p.options.servings).kcal===null?'sin datos':Math.round(planNutrition(slot.recipe,p.options.servings).kcal!-p.options.goal.kcal*p.options.shares[slot.meal]/100)} kcal</small>}<details><summary>Ver ingredientes y elaboración</summary><ul>{slot.recipe.ingredients.map((i,n)=><li key={n}>{formatQuantity(scaleQuantity(i,slot.recipe!.baseServings,p.options.servings))} {i.unit} · {i.name}{i.optional?' (opcional)':''}</li>)}</ul><ol>{slot.recipe.steps.map((s,i)=><li key={i}>{s.instruction}</li>)}</ol><p>Las cantidades anteriores son para {p.options.servings} comensales; revisa las referencias de cantidades en el texto de los pasos.</p>{libraryImage(slot.recipe.id)&&<Link to={`/receta/${slot.recipe.id}?servings=${p.options.servings}`}>Abrir ficha completa</Link>}</details></>:<p>Sin receta compatible. Este hueco no cuenta como cero calorías.</p>}<label>Cambio deseado (opcional)<input value={changes[slot.day+':'+slot.meal]||''} onChange={e=>setChanges({...changes,[slot.day+':'+slot.meal]:e.target.value})} placeholder="Ej. sustituir el pollo por pescado"/></label><div className="plan-actions"><button className="secondary-button" disabled={busy} onClick={()=>replace(slot)}>Otra de la biblioteca</button><button className="secondary-button" disabled={busy||!aiConsent} onClick={()=>void generateAlternative(slot)}>Pedir alternativa con IA</button></div></article>)}<h3>Total de las comidas planificadas · por persona</h3><Nutrition value={total}/>{p.options.goal&&<p>Diferencia energética del tramo planificado: {total.kcal===null?'no calculable':Math.round(total.kcal-p.options.goal.kcal*coverage/100)+' kcal'}. {(['proteinG','carbsG','fatG'] as const).filter(k=>p.options.goal?.[k]!==undefined).map(k=>`${labels[k]}: ${total[k]===null?'sin datos':Math.round(total[k]!-p.options.goal![k]!*coverage/100)} de diferencia. `)}</p>}</section>})}
   <section className="settings-card"><h2>Alternativas con IA</h2><p>Cada alternativa con IA consume una petición. Se propone una comida similar y se explica el cambio antes de sustituirla. No se generan imágenes.</p><label className="plan-check"><input type="checkbox" checked={aiConsent} onChange={e=>setAiConsent(e.target.checked)}/>Autorizo enviar al servicio de IA el objetivo, macros, preferencias culinarias, exclusiones y comensales para generar alternativas. No se envían peso, edad, sexo, historial ni mantenimiento.</label></section>
   <section className="settings-card"><h2><ShoppingBasket/> Compra del plan</h2><p>Se incluyen todas las semanas y solo los platos disponibles. Revisa los huecos antes de comprar.</p><label className="plan-check"><input type="checkbox" checked={subtract} onChange={e=>setSubtract(e.target.checked)}/>Descontar existencias con nombre y unidades compatibles</label><p>Los productos de despensa sin cantidad no se descuentan. No se convierte un peso en paquetes sin conocer su tamaño.</p><button className="secondary-button" disabled={busy} onClick={()=>run(()=>{replacePlanShopping(planShopping(p,settings.pantryStock,subtract));setStatus('Compra del plan actualizada. Se han conservado los demás productos.');})}>Actualizar lista de la compra</button><Link to="/lista-compra">Ver lista de la compra</Link></section>
  </>}
  {candidate&&<section className="settings-card" role="region" aria-label="Revisar alternativa"><h2>{candidate.recipe.title}</h2><p>{candidate.recipe.description}</p><Nutrition value={planNutrition(candidate.recipe,p!.options.servings)}/><p>Estimación orientativa. Revisa ingredientes y posibles diferencias nutricionales.</p><ul>{candidate.recipe.ingredients.map((i,n)=><li key={n}>{i.quantity} {i.unit} {i.name}</li>)}</ul><button className="primary-button" onClick={()=>{if(p)setPlanData({...data,plan:{...p,slots:p.slots.map(s=>s.day===candidate.slot.day&&s.meal===candidate.slot.meal?{...s,recipe:candidate.recipe}:s)}});setCandidate(undefined);setStatus('Comida sustituida. Actualiza la lista de compra.');}}>Usar esta alternativa</button><button className="secondary-button" onClick={()=>setCandidate(undefined)}>Conservar la comida anterior</button></section>}
  <details className="settings-card"><summary>Seguimiento voluntario del peso</summary><div className="plan-stack"><p>Registro descriptivo. No cambia el objetivo energético ni prescribe ajustes.</p><label className="plan-check"><input type="checkbox" checked={weightConsent} onChange={e=>setWeightConsent(e.target.checked)}/>Quiero registrar mi peso en esta sesión. Para conservarlo usaré una copia cifrada.</label><div className="plan-grid"><label>Fecha del registro<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Peso del registro (kg)<input type="number" min="0" step="0.1" value={weight} onChange={e=>setWeight(e.target.value)}/></label></div><button className="secondary-button" disabled={!weightConsent||busy} onClick={()=>run(()=>{validateWeight(date,Number(weight));setPlanData({...data,weights:[...data.weights.filter(w=>w.date!==date),{date,kg:Number(weight)}]});setWeight('');setStatus('Peso guardado en esta sesión. El objetivo no ha cambiado.');})}>Guardar o corregir peso de esta fecha</button>
   {!!weights.length&&<><svg viewBox="0 0 300 120" role="img" aria-label="Evolución del peso; fechas y valores en la tabla inferior"><polyline points={points} fill="none" stroke="currentColor" strokeWidth="2"/>{points.split(' ').map((point,i)=>{const [cx,cy]=point.split(',');return <circle key={i} cx={cx} cy={cy} r="3" fill="currentColor"/>})}</svg><p>Mínimo: {min} kg · Máximo: {max} kg · Cambio desde el inicio: {(weights.at(-1)!.kg-weights[0].kg).toFixed(1)} kg.</p><p>Gráfica en orden de registro por fecha; consulta las fechas exactas debajo.</p><table><thead><tr><th>Fecha</th><th>kg</th><th>Acciones</th></tr></thead><tbody>{weights.map(w=><tr key={w.date}><td>{w.date}</td><td>{w.kg}</td><td><button onClick={()=>{setDate(w.date);setWeight(String(w.kg));}}>Corregir</button><button disabled={busy} onClick={()=>setPlanData({...data,weights:data.weights.filter(x=>x.date!==w.date)})}>Eliminar</button></td></tr>)}</tbody></table></>}
  </div></details>
  <details className="settings-card"><summary>Guardar, recuperar o borrar mis datos</summary><div className="plan-stack"><p>La copia incluye el plan, objetivo, estimación y registro de peso. Se cifra antes de descargarse. La contraseña no se guarda ni puede recuperarse. Protege también tu dispositivo.</p><label>Contraseña de la copia<input type="password" autoComplete="new-password" minLength={12} value={password} onChange={e=>setPassword(e.target.value)}/></label><label>Repetir contraseña para guardar<input type="password" autoComplete="new-password" value={passwordRepeat} onChange={e=>setPasswordRepeat(e.target.value)}/></label><button className="secondary-button" disabled={busy} onClick={()=>void backup(false)}>Descargar copia cifrada</button><label>Archivo de copia cifrada<input type="file" accept=".json,application/json" onChange={e=>setFile(e.target.files?.[0])}/></label><p>Recuperar una copia sustituye los datos de esta sesión. El formulario también recupera las preferencias del plan guardado.</p><button className="secondary-button" disabled={busy||!file} onClick={()=>void backup(true)}>Recuperar copia y sustituir sesión</button><label className="plan-check"><input type="checkbox" checked={deleteConfirm} onChange={e=>setDeleteConfirm(e.target.checked)}/>Quiero borrar el plan, la estimación y los pesos de esta sesión</label><button className="secondary-button" disabled={busy||!deleteConfirm} onClick={()=>{setPlanData(emptyData());setConfirmed(undefined);setKcal('');setMacros({proteinG:'',carbsG:'',fatG:''});setFiber('');setPercent({protein:'',carbs:'',fat:''});setMacroMode('auto');setCandidate(undefined);setChanges({});setPersonal({weight:'',height:'',age:'',sex:'female',activity:0,eligible:false});setWeight('');setPassword('');setPasswordRepeat('');setRestrictions([]);setExcluded('');setLikes('');setFile(undefined);setAiConsent(false);setWeightConsent(false);setMode('none');setDeleteConfirm(false);setStatus('Datos de sesión borrados. Las copias descargadas y los productos enviados a compra se eliminan por separado.');}}>Borrar datos de esta sesión</button></div></details>
  <details className="settings-card"><summary>Fuentes, cálculos y límites</summary><p>Nutrición estimada por ingredientes: Public Health England, CoFID 2021 (Open Government Licence v3.0), y USDA SR Legacy 2018. Cantidad comestible × nutrientes por 100 g/ml, sumada y dividida entre comensales. Se recalcula con el escalado culinario. Opcionales excluidos; unidades y absorción de aceite estimadas. Un dato sin equivalencia no se sustituye por cero.</p><p>Los platos nuevos pueden tener información incompleta. Para recetas de IA sin equivalencias completas se muestran estimaciones de IA, que requieren revisión y no garantizan alcanzar el objetivo. La fibra se muestra cuando puede calcularse o la IA aporta una estimación.</p><p><a href="https://pubmed.ncbi.nlm.nih.gov/2305711/" target="_blank" rel="noreferrer">Mifflin–St Jeor (1990)</a> · <a href="https://www.fao.org/4/y5686e/y5686e07.htm" target="_blank" rel="noreferrer">Actividad: FAO/OMS/UNU</a> · <a href="https://www.gov.uk/government/publications/composition-of-foods-integrated-dataset-cofid" target="_blank" rel="noreferrer">CoFID</a></p><p>No se prescriben déficits, dietas terapéuticas, ayunos ni predicciones de pérdida de peso. La selección de recetas no certifica equilibrio nutricional ni ausencia de trazas. La sincronización de datos sensibles con una cuenta queda pendiente de infraestructura y validación profesional.</p></details>
 </div></AppShell>;
}
