import { ChiliIcon } from '../components/ChiliIcon';
import { SettingsAbout } from '../components/SettingsAbout';
import { Edit3, Save, Sun, Moon, Monitor } from 'lucide-react';
import { usePreviewIdentity } from '../components/PreviewIdentity';
import { ChefHat, Info, Languages, Mic, MicOff, ShieldCheck, Smartphone, Type, UserRound, UsersRound, WandSparkles } from 'lucide-react';
import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { AppShell } from '../components/AppShell';
import { ChefAvatar, CHEF_AVATARS, normalizeChefAvatar } from '../components/ChefAvatar';
import { Chip } from '../components/Chip';
import { NumberStepper } from '../components/NumberStepper';
import { useApp } from '../AppContext';
import { avatarName } from '../data/avatarNames';
import type { AppLanguage, CookingLevel, FontScale, SpiceLevel } from '../services/storage';
import { loadMicrophonePreference, requestMicrophoneAccess, saveMicrophonePreference, type MicrophonePreference } from '../utils/microphonePreference';
const fontScaleLabels:Array<{value:FontScale;label:string}>=[{value:'normal',label:'Normal'},{value:'large',label:'Grande'},{value:'xlarge',label:'Muy grande'}];
const LANGUAGE_OPTIONS:Array<{value:AppLanguage;label:string}>=[{value:'es',label:'Español'},{value:'en',label:'English'},{value:'fr',label:'Français'},{value:'de',label:'Deutsch'},{value:'it',label:'Italiano'},{value:'pt',label:'Português'},{value:'zh',label:'中文'}];
export function SettingsPage(){
 const identity=usePreviewIdentity();
 const [editing,setEditing]=useState(false);
 const navigate=useNavigate();const [saveError,setSaveError]=useState('');
 const saveAndReturn=()=>{try{updateSettings(settings);if(window.history.state?.idx>0)navigate(-1);else navigate('/')}catch{setSaveError('No se han podido guardar los cambios. Comprueba el almacenamiento del navegador e inténtalo de nuevo.')}};
 const {settings,updateSettings}=useApp(); const currentAvatar=normalizeChefAvatar(settings.avatarEmoji); const [micPreference,setMicPreference]=useState<MicrophonePreference>(()=>loadMicrophonePreference()); const [micBusy,setMicBusy]=useState(false);
 const enableMicrophone=async()=>{if(micBusy)return;setMicBusy(true);setMicPreference(await requestMicrophoneAccess());setMicBusy(false)}; const disableMicrophone=()=>{saveMicrophonePreference('disabled');setMicPreference('disabled')};
 return <AppShell><div className="simple-page-header light-header"><span className="eyebrow">TU PERFIL DE COCINA</span><div className="settings-header-row"><h1>Ajustes</h1><button className="settings-save" onClick={saveAndReturn}><Save size={19}/><span>Guardar cambios</span></button></div><p>Preferencias para que Chef Voldi se adapte a tu forma de cocinar.</p></div><div className="page-content nav-safe settings-v03">
  <section className="settings-card"><div className="settings-profile-heading"><ChefAvatar avatar={settings.avatarEmoji} size={74} showHat={false}/><div><strong>{settings.displayName||'Tu perfil'}</strong><button aria-expanded={editing} onClick={()=>setEditing(v=>!v)}><Edit3 size={18}/>{editing?'Terminar edición':'Editar perfil'}</button></div></div></section>
  {editing&&<><section className="settings-card"><div className="settings-card-title"><UserRound size={20}/><div><strong>Datos de usuario</strong><small>{identity?'Administrador de pruebas · cuenta verificada':'Datos de acceso del usuario.'}</small></div></div><div className="settings-user-fields"><label><span>Nombre</span><input value={settings.displayName} onChange={e=>updateSettings({displayName:e.target.value})} autoComplete="name" placeholder="Tu nombre"/></label><label><span>Usuario / correo</span><input value={settings.loginUser} readOnly autoComplete="username" placeholder="Usuario"/></label></div>{identity?<div className="pantry-basics-note"><ShieldCheck size={15}/><span>Acceso automático con tu cuenta verificada. {identity.stableUrl&&<a href={identity.stableUrl}>Enlace fijo de pruebas</a>} · <a href="/cdn-cgi/access/logout">Cerrar sesión</a></span></div>:<div className="pantry-basics-note"><ShieldCheck size={15}/> La contraseña no se recupera ni se muestra desde Ajustes. En esta beta se conserva solo un derivado criptográfico local. El acceso definitivo se conectará al backend antes de producción.</div>}</section>
  <section className="settings-card profile-settings-card"><div className="settings-card-title"><ChefHat size={20}/><div><strong>Tu avatar</strong><small>Elige uno de los 16 personajes de Chef Voldi.</small></div></div><div className="profile-preview-row"><ChefAvatar avatar={settings.avatarEmoji} size={74} showHat={false}/><div><strong>{avatarName(currentAvatar)}</strong><small>Será tu asistente en navegación, esperas y PDF.</small></div></div><div className="avatar-gallery" aria-label="Avatares disponibles">{CHEF_AVATARS.map(a=><button type="button" className={currentAvatar===a.id?'active':''} key={a.id} onClick={()=>updateSettings({avatarEmoji:a.id,profileImage:undefined})} aria-label={`Elegir avatar ${avatarName(a.id)}`} title={avatarName(a.id)}><ChefAvatar avatar={a.id} size={48} showHat={false}/></button>)}</div></section>
  </>}
  <section className="settings-card"><div className="settings-card-title"><Sun/><strong>Tema</strong></div><div className="chip-row">{([{value:'light',label:'Claro',Icon:Sun},{value:'dark',label:'Oscuro',Icon:Moon},{value:'auto',label:'Automático',Icon:Monitor}] as const).map(({value,label,Icon})=><Chip key={value} selected={(settings.theme||'auto')===value} onClick={()=>updateSettings({theme:value})}><Icon size={16}/> {label}</Chip>)}</div></section>
  <section className="settings-card"><div className="settings-card-title"><WandSparkles size={20}/><div><strong>Biblioteca primero</strong><small>Recetas listas para cocinar, con imágenes ya preparadas.</small></div></div><p className="pantry-basics-note">La búsqueda consulta primero la biblioteca. Puedes usar IA para crear otra receta o personalizarla.</p><label className="settings-toggle"><input type="checkbox" checked={settings.autoAiFallback!==false} onChange={e=>updateSettings({autoAiFallback:e.target.checked})}/> Usar IA si no hay una receta adecuada para mis ingredientes</label></section>
  <section className="settings-card"><div className="settings-card-title">{micPreference==='enabled'?<Mic size={20}/>:<MicOff size={20}/>}<div><strong>Micrófono</strong><small>Controla el dictado por voz.</small></div></div><div className="pantry-basics-note">{micPreference==='enabled'?'Micrófono activado.':micPreference==='unsupported'?'Este dispositivo no permite micrófono desde la app.':'Micrófono desactivado.'}</div><div className="settings-mic-actions">{micPreference!=='enabled'?<button type="button" className="secondary-button" onClick={()=>void enableMicrophone()} disabled={micBusy}>{micBusy?'Solicitando permiso…':'Activar micrófono'}</button>:<button type="button" className="secondary-button" onClick={disableMicrophone}>Desactivar en Chef Voldi</button>}</div></section>
  <section className="settings-card"><div className="settings-card-title"><Languages size={20}/><div><strong>Idioma</strong><small>Interfaz en desarrollo. La biblioteca fija sigue en español; las recetas nuevas por IA usan el idioma elegido.</small></div></div><select className="settings-select" value={settings.language} onChange={e=>updateSettings({language:e.target.value as AppLanguage})}>{LANGUAGE_OPTIONS.map(o=><option value={o.value} key={o.value}>{o.label}</option>)}</select></section>
  <section className="control-card"><div className="control-row"><div className="control-title"><UsersRound size={19}/><div><strong>Comensales habituales</strong><small>Valor inicial</small></div></div><NumberStepper value={settings.defaultServings} onChange={v=>updateSettings({defaultServings:v})}/></div></section>
  <section className="settings-card"><div className="settings-card-title"><Type size={20}/><div><strong>Tamaño de texto</strong><small>Legibilidad de toda la aplicación.</small></div></div><div className="chip-row">{fontScaleLabels.map(o=><Chip key={o.value} selected={settings.fontScale===o.value} onClick={()=>updateSettings({fontScale:o.value})}>{o.label}</Chip>)}</div></section>
  <section className="settings-card"><div className="settings-card-title"><ChefHat size={20}/><div><strong>Nivel de cocina</strong><small>Afecta al detalle y dificultad recomendada.</small></div></div><div className="chip-row">{(['Principiante','Intermedio','Avanzado'] as CookingLevel[]).map(v=><Chip key={v} selected={settings.cookingLevel===v} onClick={()=>updateSettings({cookingLevel:v})}>{v}</Chip>)}</div></section>
  <section className="settings-card"><div className="settings-card-title"><ChiliIcon/><div><strong>Picante habitual</strong><small>Preferencia, no restricción.</small></div></div><div className="chip-row">{(['Nada','Suave','Medio','Alto'] as SpiceLevel[]).map(v=><Chip key={v} selected={settings.spiceLevel===v} onClick={()=>updateSettings({spiceLevel:v})}>{v}</Chip>)}</div></section>
  <section className="editorial-card small-info"><Smartphone size={21}/><div><strong>PWA privada</strong><p>La versión de pruebas se instala desde HTTPS y funciona como app.</p></div></section><section className="editorial-card small-info"><Info size={21}/><div><strong>Versión de prueba</strong><p>{__BUILD_COMMIT__?`${__BUILD_COMMIT__.slice(0,12)}${__BUILD_BRANCH__?` · ${__BUILD_BRANCH__}`:''}`:'Build local / sin metadatos de despliegue'}</p></div></section><section className="editorial-card small-info"><Info size={21}/><div><strong>Fase 1</strong><p>Versión destinada a beta privada con usuarios reales.</p></div></section>
 {saveError&&<p role="alert">{saveError}</p>}
 <div className="settings-save-footer"><button className="entry-primary" onClick={saveAndReturn}><Save size={19}/> Guardar cambios</button></div>
 <SettingsAbout url={identity?.stableUrl||window.location.origin+import.meta.env.BASE_URL}/>
 </div></AppShell>;
}
