import { ChefHat, Eye, EyeOff, Info, KeyRound, Languages, Mic, MicOff, Smartphone, Type, UserRound, UsersRound, WandSparkles } from 'lucide-react';
import { useState } from 'react';
import { AppShell } from '../components/AppShell';
import { ChefAvatar, CHEF_AVATARS, normalizeChefAvatar } from '../components/ChefAvatar';
import { Chip } from '../components/Chip';
import { NumberStepper } from '../components/NumberStepper';
import { useApp } from '../AppContext';
import { avatarName } from '../data/avatarNames';
import type { AppLanguage, CookingLevel, FontScale, SpiceLevel } from '../services/storage';
import { loadMicrophonePreference, requestMicrophoneAccess, saveMicrophonePreference, type MicrophonePreference } from '../utils/microphonePreference';
const fontScaleLabels:Array<{value:FontScale;label:string}>=[{value:'normal',label:'Normal'},{value:'large',label:'Grande'},{value:'xlarge',label:'Muy grande'}];
const LANGUAGE_OPTIONS:Array<{value:AppLanguage;label:string}>=[{value:'es',label:'Español'},{value:'en',label:'English'},{value:'fr',label:'Français'},{value:'de',label:'Deutsch'},{value:'it',label:'Italiano'},{value:'pt',label:'Português'},{value:'zh',label:'中文'}];
export function SettingsPage(){
 const {settings,updateSettings}=useApp(); const currentAvatar=normalizeChefAvatar(settings.avatarEmoji); const [showPassword,setShowPassword]=useState(false); const [micPreference,setMicPreference]=useState<MicrophonePreference>(()=>loadMicrophonePreference()); const [micBusy,setMicBusy]=useState(false);
 const enableMicrophone=async()=>{if(micBusy)return;setMicBusy(true);setMicPreference(await requestMicrophoneAccess());setMicBusy(false)}; const disableMicrophone=()=>{saveMicrophonePreference('disabled');setMicPreference('disabled')};
 return <AppShell hideBack><div className="simple-page-header light-header"><span className="eyebrow">TU PERFIL DE COCINA</span><h1>Ajustes</h1><p>Preferencias para que The Chef se adapte a tu forma de cocinar.</p></div><div className="page-content nav-safe settings-v03">
  <section className="settings-card"><div className="settings-card-title"><UserRound size={20}/><div><strong>Datos de usuario</strong><small>Datos de acceso del usuario.</small></div></div><div className="settings-user-fields"><label><span>Nombre</span><input value={settings.displayName} onChange={e=>updateSettings({displayName:e.target.value})} autoComplete="name" placeholder="Tu nombre"/></label><label><span>Usuario de acceso</span><input value={settings.loginUser} onChange={e=>updateSettings({loginUser:e.target.value})} autoComplete="username" placeholder="Usuario"/></label><label><span>Contraseña</span><div className="password-field"><KeyRound size={17}/><input type={showPassword?'text':'password'} value={settings.loginPassword} onChange={e=>updateSettings({loginPassword:e.target.value})} autoComplete="current-password" placeholder="Contraseña"/><button type="button" onClick={()=>setShowPassword(v=>!v)} aria-label={showPassword?'Ocultar contraseña':'Mostrar contraseña'}>{showPassword?<EyeOff size={19}/>:<Eye size={19}/>}</button></div></label></div><div className="pantry-basics-note">En esta beta los datos se guardan en este dispositivo. El acceso definitivo se conectará al backend antes de producción.</div></section>
  <section className="settings-card profile-settings-card"><div className="settings-card-title"><ChefHat size={20}/><div><strong>Tu avatar</strong><small>Elige uno de los 16 personajes de The Chef.</small></div></div><div className="profile-preview-row"><ChefAvatar avatar={settings.avatarEmoji} size={74} showHat={false}/><div><strong>{avatarName(currentAvatar)}</strong><small>Será tu asistente en navegación, esperas y PDF.</small></div></div><div className="avatar-gallery" aria-label="Avatares disponibles">{CHEF_AVATARS.map(a=><button type="button" className={currentAvatar===a.id?'active':''} key={a.id} onClick={()=>updateSettings({avatarEmoji:a.id,profileImage:undefined})} aria-label={`Elegir avatar ${avatarName(a.id)}`} title={avatarName(a.id)}><ChefAvatar avatar={a.id} size={48} showHat={false}/></button>)}</div></section>
  <section className="settings-card"><div className="settings-card-title"><WandSparkles size={20}/><div><strong>Recetas existentes ↔ IA</strong><small>Elige cuánto quieres apoyarte en generación y personalización con IA.</small></div></div><input aria-label="Porcentaje de uso de IA" type="range" min="0" max="100" step="10" value={settings.aiPreference} onChange={e=>updateSettings({aiPreference:Number(e.target.value)})} style={{width:'100%'}}/><div className="pantry-basics-note"><strong>{settings.aiPreference}% IA</strong> · {100-settings.aiPreference}% catálogo. No cambia la calidad de la app: cambia cuánto contenido se genera frente a reutilizar recetas validadas.</div></section>
  <section className="settings-card"><div className="settings-card-title">{micPreference==='enabled'?<Mic size={20}/>:<MicOff size={20}/>}<div><strong>Micrófono</strong><small>Controla el dictado por voz.</small></div></div><div className="pantry-basics-note">{micPreference==='enabled'?'Micrófono activado.':micPreference==='unsupported'?'Este dispositivo no permite micrófono desde la app.':'Micrófono desactivado.'}</div><div className="settings-mic-actions">{micPreference!=='enabled'?<button type="button" className="secondary-button" onClick={()=>void enableMicrophone()} disabled={micBusy}>{micBusy?'Solicitando permiso…':'Activar micrófono'}</button>:<button type="button" className="secondary-button" onClick={disableMicrophone}>Desactivar en The Chef</button>}</div></section>
  <section className="settings-card"><div className="settings-card-title"><Languages size={20}/><div><strong>Idioma</strong><small>Idioma de interfaz y contenidos generados.</small></div></div><select className="settings-select" value={settings.language} onChange={e=>updateSettings({language:e.target.value as AppLanguage})}>{LANGUAGE_OPTIONS.map(o=><option value={o.value} key={o.value}>{o.label}</option>)}</select></section>
  <section className="control-card"><div className="control-row"><div className="control-title"><UsersRound size={19}/><div><strong>Comensales habituales</strong><small>Valor inicial</small></div></div><NumberStepper value={settings.defaultServings} onChange={v=>updateSettings({defaultServings:v})}/></div></section>
  <section className="settings-card"><div className="settings-card-title"><Type size={20}/><div><strong>Tamaño de texto</strong><small>Legibilidad de toda la aplicación.</small></div></div><div className="chip-row">{fontScaleLabels.map(o=><Chip key={o.value} selected={settings.fontScale===o.value} onClick={()=>updateSettings({fontScale:o.value})}>{o.label}</Chip>)}</div></section>
  <section className="settings-card"><div className="settings-card-title"><ChefHat size={20}/><div><strong>Nivel de cocina</strong><small>Afecta al detalle y dificultad recomendada.</small></div></div><div className="chip-row">{(['Principiante','Intermedio','Avanzado'] as CookingLevel[]).map(v=><Chip key={v} selected={settings.cookingLevel===v} onClick={()=>updateSettings({cookingLevel:v})}>{v}</Chip>)}</div></section>
  <section className="settings-card"><div className="settings-card-title"><strong>Picante habitual</strong><small>Preferencia, no restricción.</small></div><div className="chip-row">{(['Nada','Suave','Medio','Alto'] as SpiceLevel[]).map(v=><Chip key={v} selected={settings.spiceLevel===v} onClick={()=>updateSettings({spiceLevel:v})}>{v}</Chip>)}</div></section>
  <section className="editorial-card small-info"><Smartphone size={21}/><div><strong>PWA privada</strong><p>La versión de pruebas se instala desde HTTPS y funciona como app.</p></div></section><section className="editorial-card small-info"><Info size={21}/><div><strong>Fase 1</strong><p>Versión destinada a beta privada con usuarios reales.</p></div></section>
 </div></AppShell>;
}
