import {useEffect,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
import {Copy,Download,Share2,X,Instagram,Facebook,Music2} from 'lucide-react';
import type {Recipe} from '../domain/types';
import {createSocialCard,downloadSocialCard,socialCaption,type SocialFormat} from '../services/socialShare';
import './SocialShareDialog.css';
export function SocialShareDialog({recipe,servings,imageUrl,onClose}:{recipe:Recipe;servings:number;imageUrl?:string;onClose:()=>void}){
 const dialog=useRef<HTMLDialogElement>(null);const [format,setFormat]=useState<SocialFormat>('post');
 const [card,setCard]=useState<{file:File;url:string;format:SocialFormat}>();const [error,setError]=useState('');const [status,setStatus]=useState('');const [sharing,setSharing]=useState(false);
 const [network,setNetwork]=useState('');
 const guides:Record<string,string>={Instagram:'Elige Instagram en el menú del móvil si aparece. Si no, descarga la imagen, abre Instagram y crea una publicación o historia. Pega el texto en el pie de foto; en historias puedes añadir el enlace con la herramienta de enlaces.',Facebook:'Elige Facebook en el menú del móvil si aparece. También puedes descargar la imagen y adjuntarla a una publicación, pegando el texto y el enlace.',TikTok:'Descarga la imagen y añádela desde la opción de fotos de TikTok, o selecciónalo en el menú del móvil si aparece. Pega el texto en la descripción.',X:'Elige X en el menú del móvil si aparece, o descarga la imagen y adjúntala a una nueva publicación. Pega el texto y ajústalo al límite que permita tu cuenta.'};
 const caption=socialCaption(recipe,servings);const ready=card?.format===format?card:undefined;
 useEffect(()=>{const focused=document.activeElement;const el=dialog.current!;el.showModal();const previous=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{el.close();document.body.style.overflow=previous;if(focused instanceof HTMLElement)focused.focus();}},[]);
 useEffect(()=>{let disposed=false,url:string|undefined;setCard(undefined);setError('');setStatus('');if(!imageUrl){setError('Espera a que cargue la foto de la receta para preparar la tarjeta.');return;}
 void createSocialCard(recipe,servings,format,imageUrl).then(file=>{if(disposed)return;url=URL.createObjectURL(file);setCard({file,url,format});}).catch(()=>{if(!disposed)setError('No se ha podido preparar esta foto. Vuelve a abrir la opción cuando la imagen esté disponible.');});return()=>{disposed=true;if(url)URL.revokeObjectURL(url);};},[recipe.id,servings,format,imageUrl]);
 const share=async()=>{if(!ready||sharing)return;setStatus('');setSharing(true);try{
   if(!navigator.share||!navigator.canShare?.({files:[ready.file]})){downloadSocialCard(ready.file);setStatus('Imagen descargada. Súbela desde la red social y copia el texto para acompañarla.');return;}
   // The file is already prepared, preserving the click's native user activation.
   await navigator.share({files:[ready.file],title:recipe.title,text:caption});setStatus('Tarjeta enviada al menú de compartir.');
 }catch(e){if(!(e instanceof DOMException&&e.name==='AbortError'))setStatus('No se ha podido abrir el menú. Puedes descargar la imagen y copiar el texto.');}finally{setSharing(false);}};
 return createPortal(<dialog ref={dialog} className="social-share-dialog" aria-labelledby="social-share-title" onCancel={e=>{e.preventDefault();if(!sharing)onClose();}} onClick={e=>{if(e.target===e.currentTarget&&!sharing)onClose();}}><div className="social-share-content"><header><h2 id="social-share-title">Compartir en redes</h2><button className="icon-button" aria-label="Cerrar compartir en redes" onClick={onClose} disabled={sharing}><X/></button></header><div className="social-format-options" role="group" aria-label="Formato de imagen"><button aria-pressed={format==='post'} disabled={sharing} onClick={()=>setFormat('post')}>Publicación · 4:5</button><button aria-pressed={format==='story'} disabled={sharing} onClick={()=>setFormat('story')}>Historia · 9:16</button></div>{ready?<img className="social-share-preview" src={ready.url} alt={`Tarjeta de ${recipe.title}`}/>:<p role="status">{error||'Preparando la tarjeta…'}</p>}<div className="social-network-options" role="group" aria-label="Red social">{[['Instagram',Instagram],['Facebook',Facebook],['TikTok',Music2],['X',X]].map(([name,Icon])=>{const LabelIcon=Icon as typeof Instagram;return <button className="secondary-button" type="button" key={String(name)} aria-pressed={network===name} onClick={()=>setNetwork(String(name))}><LabelIcon size={20}/>{String(name)}</button>})}</div>{network&&<p role="status">{guides[network]} La publicación se confirma dentro de la red social.</p>}<p>Elige una aplicación compatible en el menú de tu móvil. Si no aparece tu red social, descarga la imagen y súbela desde allí.</p><label className="social-caption">Texto para acompañar la imagen<textarea aria-label="Texto para compartir" readOnly value={caption} rows={5}/></label><small>El enlace abre la app, no una copia pública de tu receta. Mientras estemos en pruebas, dirige a la preview.</small><div className="social-share-actions"><button className="secondary-button" disabled={!ready||sharing} onClick={()=>void share()}><Share2 size={18}/> Compartir imagen</button><button className="secondary-button" disabled={!ready||sharing} onClick={()=>{if(ready){downloadSocialCard(ready.file);setStatus('Imagen descargada.');}}}><Download size={18}/> Descargar imagen</button><button className="secondary-button" disabled={sharing} onClick={()=>{void navigator.clipboard?.writeText(caption).then(()=>setStatus('Texto copiado.')).catch(()=>setStatus('Selecciona el texto y cópialo manualmente.'));if(!navigator.clipboard)setStatus('Selecciona el texto y cópialo manualmente.');}}><Copy size={18}/> Copiar texto y enlace</button></div>{status&&<p role="status">{status}</p>}</div></dialog>,document.body);
}
