import fs from 'node:fs';
const read=p=>fs.readFileSync(p,'utf8'); const checks=[]; const ok=(name,condition)=>checks.push({name,condition});
const app=read('src/App.tsx'),shell=read('src/components/AppShell.tsx'),home=read('src/pages/HomePage.tsx'),recipe=read('src/pages/RecipePage.tsx'),results=read('src/pages/ResultsPage.tsx'),cook=read('src/pages/CookPage.tsx'),stepTimer=read('src/components/StepTimer.tsx'),directRecipe=read('src/services/directRecipeGateway.ts'),pantry=read('src/pages/PantryCookPage.tsx'),photo=read('src/pages/PhotoRecipePage.tsx'),shopping=read('src/pages/ShoppingListPage.tsx'),context=read('src/AppContext.tsx'),i18n=read('src/components/UiI18n.tsx'),types=read('src/domain/types.ts'),gateway=read('src/services/aiProposalGateway.ts'),hybrid=read('src/services/hybridRecommendationEngine.ts'),mock=read('src/services/mockRecommendationEngine.ts'),intent=read('src/utils/desireIntent.ts'),options=read('src/components/CookingOptions.tsx'),guard=read('src/services/restrictionGuard.ts'),cuisine=read('src/components/CuisineSelect.tsx'),storage=read('src/services/storage.ts'),access=read('src/pages/AccessPage.tsx'),settings=read('src/pages/SettingsPage.tsx'),localAuth=read('src/services/localAuth.ts'),tour=read('src/components/GuidedTour.tsx'),pdf=read('src/services/recipePdf.ts'),stepScaling=read('src/utils/scaleStepInstruction.ts'),homeCss=read('src/home-v04.css'),pkg=JSON.parse(read('package.json'));
ok('Ruta Crear tu receta',app.includes('/crear-receta'));
ok('Ruta Tutorial',app.includes('/tutorial'));
ok('Avatar flotante en todas las pantallas',shell.includes('createPortal')&&shell.includes('chef-draggable-avatar')&&!shell.includes('!isHome && !hideProfile'));
ok('Sin BottomNav en AppShell',!shell.includes('BottomNav'));
ok('Avatar disponible en Lista de compra',!shopping.includes('hideProfile'));
ok('Nombre Abre la despensa',home.includes('Abre la despensa')&&pantry.includes('Abre la despensa'));
ok('Foto Receta',home.includes('Foto Receta'));
ok('Sin boton Crear tu receta',!home.includes('Crear tu receta'));
ok('Receta directa sin pantalla de propuesta',pantry.includes('generateDirectRecipe')&&read('src/pages/DesirePage.tsx').includes('generateDirectRecipe')&&hybrid.includes('PROPOSAL_COUNT=1')&&!results.includes('ProposalCard'));
ok('Tiempo máximo 120',read('src/components/CookingOptions.tsx').includes('max={120}')&&directRecipe.includes('recipe.prepMinutes+recipe.cookMinutes>request.maxMinutes'));
ok('Recipe sin panel elaboración duplicado',!recipe.includes("'elaboration'"));
ok('CTA Elaboración',recipe.includes('> Elaboración</button>'));
ok('Ficha foto-título-resumen-nutrición',recipe.indexOf('recipe-hero')<recipe.indexOf('recipe-title-block')&&recipe.indexOf('recipe-title-block')<recipe.indexOf('recipe-summary-content')&&recipe.indexOf('recipe-summary-content')<recipe.indexOf('nutrition-card nutrition-card-priority'));
ok('Imagen preparada antes de abrir ficha',directRecipe.includes('await getRecipeImage(recipe)')&&read('src/pages/DesirePage.tsx').includes('navigate(`/receta/${result.recipe.id}`)'));
ok('Reintento de imagen sin regenerar receta',directRecipe.includes('getRecipeImage(recipe).catch')&&recipe.includes('Reintentar imagen'));
ok('Variantes versionadas',recipe.includes('· v${version}'));
ok('Timer con deadline real',read('src/components/timerStore.ts').includes('deadline')&&read('src/components/timerStore.ts').includes('Date.now()')&&stepTimer.includes('role="timer"'));
ok('Cook sin BottomNav',!cook.includes('BottomNav'));
ok('Foto corrección confirmada',photo.includes('CONFIRMADOS por el usuario'));
ok('Métrica IA',gateway.includes('recordAiUsage'));
ok('Idioma seleccionado llega a IA',gateway.includes('Idioma de salida obligatorio'));
ok('Capa multidioma activa',app.includes('<UiI18n>')&&i18n.includes('Apri la dispensa'));
ok('Compra manual persiste entre recetas',context.includes('existingIsManual')&&context.includes('!item.recipeId || item.recipeId === recipeId'));
ok('Proposal nutrition',/nutritionPerServing\?\s*:\s*NutritionSummary/.test(types));
ok('jsPDF parcheado',/^\^?4\.2\.1$/.test(pkg.dependencies?.jspdf??''));
ok('Solo ingredientes seleccionados en propuesta',pantry.includes("const available=selectedItems.map")&&pantry.includes("pantryIngredients:available"));
ok('Preferencia IA para una propuesta',hybrid.includes("Math.round(preference/100)")&&hybrid.includes('PROPOSAL_COUNT=1'));
ok('Tutorial sin BottomNav obsoleto',!tour.includes('data-tour="bottom-nav"')&&!tour.includes('Empezar a cocinar'));
ok('Contraseña no expuesta en Ajustes',!settings.includes('settings.loginPassword')&&!settings.includes('Mostrar contraseña'));
ok('Credencial local derivada con PBKDF2',localAuth.includes("name:'PBKDF2'")&&localAuth.includes("hash:'SHA-256'")&&localAuth.includes('150000'));
ok('Acceso migra contraseña legado',access.includes('hasLocalCredential')&&access.includes('saveLocalCredential')&&access.includes('loginPassword: undefined'));
ok('Restricciones deterministas en fallback',mock.includes('recipeViolatesRestrictions')&&guard.includes('GROUPS'));
ok('Restricciones verificadas tras generación IA',gateway.includes('assertRecipeRestrictions(recipe,request.restrictions)'));
ok('Restricciones disponibles en Abre la nevera',read('src/components/CookingOptions.tsx').includes('Restricciones / exclusiones')&&pantry.includes('...cookingRequestOptions(options.value)'));
ok('Tengo y Me falta persisten por receta',recipe.includes('loadMissingIngredients')&&recipe.includes('saveMissingIngredients'));
ok('Temporizador editable por paso',cook.includes("timerId={'recipe:'")&&read('src/pages/TechniquesPage.tsx').includes("timerId={'technique:'")&&stepTimer.includes('Minutos del temporizador')&&stepTimer.includes('Segundos del temporizador')&&read('src/components/timerStore.ts').includes('playAlarm'));
ok('Otra cocina editable',cuisine.includes('Otra cocina…')&&cuisine.includes('Escribe el tipo de cocina'));
ok('Tiempo y dificultad son límites locales',mock.includes('r.prepMinutes+r.cookMinutes<=request.maxMinutes')&&mock.includes('difficultyRank[r.difficulty]<=difficultyRank[request.difficulty]'));
ok('Sustitución aceptada mediante variante',recipe.includes('Usar sustituto')&&recipe.includes('Ajusta cantidades, pasos, tiempos y valores nutricionales'));
ok('Inventario ayuda sin marcar Tengo automáticamente',recipe.includes('availableNames')&&recipe.includes('findAvailableSubstitute')&&recipe.includes('saveHaveIngredients')&&!recipe.includes('ingredientNamesMatch'));
ok('Cantidades de pasos escalan en cocina y PDF',cook.includes('scaleStepInstruction(recipe,step.instruction,servings)')&&pdf.includes('scaleStepInstruction(recipe,s.instruction,servings)')&&stepScaling.includes('scaleQuantity'));
ok('PDF disponible sin carga tardía de jsPDF',pdf.includes("import { jsPDF } from 'jspdf'")&&!pdf.includes("await import('jspdf')"));
ok('Home sin URLs CSS obsoletas',!homeCss.includes("./home-pantry.jpg")&&!homeCss.includes("./home-desire.jpg"));
ok('Propuestas IA respetan límites duros',hybrid.includes('proposalWithinLimits')&&hybrid.includes('proposal.minutes>request.maxMinutes')&&hybrid.includes('DIFFICULTY_RANK[proposal.difficulty]>DIFFICULTY_RANK[request.difficulty]'));
ok('Nutrición escalada evita falsa precisión',recipe.includes('El escalado culinario puede variar ligeramente los valores'));
ok('Personalización sin límite temporal por defecto',options.includes('maxMinutes:previous?.maxMinutes')&&options.includes('Sin límite')&&!options.includes('previous?.maxMinutes??60'));
ok('Picante sin aplicar por defecto',options.includes('spiceLevel:previous?.spiceLevel')&&options.includes('Sin aplicar')&&!options.includes('settings.spiceLevel'));
ok('Fallback conserva intención culinaria',hybrid.includes('proposalMatchesDesireIntent')&&mock.includes('recipeMatchesDesireIntent')&&intent.includes('No se mostrará otra receta')===false&&intent.includes('required.length===1?matched===1:matched>=2'));
ok('Ingredientes empiezan en estado neutro',recipe.includes('Ningún ingrediente se marca automáticamente')&&!recipe.includes('isDefaultWater')&&!recipe.includes('ingredientNamesMatch')&&recipe.includes("status:'have'|'missing'|'neutral'"));

const failed=checks.filter(c=>!c.condition);for(const c of checks)console.log(`${c.condition?'✓':'✗'} ${c.name}`);if(failed.length){console.error(`\n${failed.length} comprobaciones fallidas.`);process.exit(1)}console.log(`\n${checks.length} comprobaciones de Fase 1 superadas.`);
