import fs from 'node:fs';
const read=p=>fs.readFileSync(p,'utf8'); const checks=[]; const ok=(name,condition)=>checks.push({name,condition});
const app=read('src/App.tsx'),shell=read('src/components/AppShell.tsx'),home=read('src/pages/HomePage.tsx'),recipe=read('src/pages/RecipePage.tsx'),cook=read('src/pages/CookPage.tsx'),pantry=read('src/pages/PantryCookPage.tsx'),photo=read('src/pages/PhotoRecipePage.tsx'),shopping=read('src/pages/ShoppingListPage.tsx'),context=read('src/AppContext.tsx'),i18n=read('src/components/UiI18n.tsx'),types=read('src/domain/types.ts'),gateway=read('src/services/aiProposalGateway.ts'),pkg=JSON.parse(read('package.json'));
ok('Ruta Crear tu receta',app.includes('/crear-receta'));
ok('Ruta Tutorial',app.includes('/tutorial'));
ok('Inicio sin avatar flotante',shell.includes('!isHome && !hideProfile'));
ok('Sin BottomNav en AppShell',!shell.includes('BottomNav'));
ok('Avatar disponible en Lista de compra',!shopping.includes('hideProfile'));
ok('Nombre Abre la nevera',home.includes('Abre la nevera...')&&pantry.includes('ABRE LA NEVERA'));
ok('Foto Receta',home.includes('Foto Receta'));
ok('Crear tu receta',home.includes('Crear tu receta'));
ok('Dos propuestas',pantry.includes('slice(0,2)'));
ok('Tiempo máximo 120',pantry.includes('max={120}'));
ok('Recipe sin panel elaboración duplicado',!recipe.includes("'elaboration'"));
ok('CTA Elaboración',recipe.includes('> Elaboración</button>'));
ok('Variantes versionadas',recipe.includes('· v${version}'));
ok('Timer con deadline real',cook.includes('deadline')&&cook.includes('Date.now()'));
ok('Cook sin BottomNav',!cook.includes('BottomNav'));
ok('Foto corrección confirmada',photo.includes('CONFIRMADOS por el usuario'));
ok('Métrica IA',gateway.includes('recordAiUsage'));
ok('Idioma seleccionado llega a IA',gateway.includes('Idioma de salida obligatorio'));
ok('Capa multidioma activa',app.includes('<UiI18n>')&&i18n.includes('Apri il frigo'));
ok('Compra manual persiste entre recetas',context.includes('existingIsManual')&&context.includes('!item.recipeId || item.recipeId === recipeId'));
ok('Proposal nutrition',/nutritionPerServing\?\s*:\s*NutritionSummary/.test(types));
ok('jsPDF parcheado',/^\^?4\.2\.1$/.test(pkg.dependencies?.jspdf??''));
const failed=checks.filter(c=>!c.condition);for(const c of checks)console.log(`${c.condition?'✓':'✗'} ${c.name}`);if(failed.length){console.error(`\n${failed.length} comprobaciones fallidas.`);process.exit(1)}console.log(`\n${checks.length} comprobaciones de Fase 1 superadas.`);
